/**
 * PHASE_HOME_ALERT_RUNTIME_BINDING — HOME_ALERT sheet read / claim / resolve.
 */
var CBV_HOME_ALERT_SHEET = 'HOME_ALERT';

var CBV_HOME_ALERT_STATUS = {
  OPEN: 'OPEN',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_RESPONSE: 'WAITING_RESPONSE',
  ESCALATED: 'ESCALATED',
  RESOLVED: 'RESOLVED',
  AUTO_CLEARED: 'AUTO_CLEARED',
  EXPIRED: 'EXPIRED',
};

var CBV_HOME_ALERT_TERMINAL = [
  CBV_HOME_ALERT_STATUS.RESOLVED,
  CBV_HOME_ALERT_STATUS.AUTO_CLEARED,
  CBV_HOME_ALERT_STATUS.EXPIRED,
];

var CBV_HOME_ALERT_ACTIVE = [
  CBV_HOME_ALERT_STATUS.OPEN,
  CBV_HOME_ALERT_STATUS.ACKNOWLEDGED,
  CBV_HOME_ALERT_STATUS.IN_PROGRESS,
  CBV_HOME_ALERT_STATUS.WAITING_RESPONSE,
  CBV_HOME_ALERT_STATUS.ESCALATED,
];

var CBV_HOME_ALERT_ACTIONS = [
  'health',
  'getTodaySummary',
  'claimHomeAlert',
  'resolveHomeAlert',
];
