/** Fallback only when ENUM_DICTIONARY sheet is missing or empty. Prefer getEnumValues() / assertValidEnumValue(). */
const CBV_ENUM = {
  ROLE: ['ADMIN', 'OPERATOR', 'ACCOUNTANT', 'VIEWER'],
  HO_SO_TYPE: ['HTX', 'XA_VIEN', 'XE', 'TAI_XE'],
  HO_SO_STATUS: ['NEW', 'ACTIVE', 'INACTIVE', 'ARCHIVED'],
  FILE_GROUP: ['CCCD', 'GPLX', 'DANG_KY_XE', 'HOP_DONG', 'KHAC'],
  TASK_STATUS: ['NEW', 'ASSIGNED', 'IN_PROGRESS', 'WAITING', 'DONE', 'CANCELLED', 'ARCHIVED'],
  TASK_TYPE: ['GENERAL', 'HO_SO', 'FINANCE', 'OPERATION'],
  PRIORITY: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'],
  ATTACHMENT_TYPE: ['FILE', 'IMAGE', 'LINK'],
  UPDATE_TYPE: ['NOTE', 'QUESTION', 'ANSWER', 'STATUS_CHANGE'],
  FINANCE_TYPE: ['INCOME', 'EXPENSE'],
  FINANCE_STATUS: ['NEW', 'CONFIRMED', 'CANCELLED', 'ARCHIVED'],
  FIN_CATEGORY: ['VAN_HANH', 'NHIEN_LIEU', 'SUA_CHUA', 'LUONG', 'THU_KHAC', 'CHI_KHAC'],
  PAYMENT_METHOD: ['CASH', 'BANK', 'OTHER'],
  MASTER_CODE_STATUS: ['ACTIVE', 'INACTIVE', 'ARCHIVED'],
  USER_DIRECTORY_STATUS: ['ACTIVE', 'INACTIVE', 'ARCHIVED']
};
