/**
 * CBV Enum Seed - Idempotent ENUM_DICTIONARY initialization.
 * Creates sheet if missing, inserts missing rows only. Does not duplicate.
 */
var ENUM_DICTIONARY_HEADERS = ['ID', 'ENUM_GROUP', 'ENUM_VALUE', 'DISPLAY_TEXT', 'SORT_ORDER', 'IS_ACTIVE', 'NOTE', 'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY'];

var ENUM_SEED_SPEC = [
  { ENUM_GROUP: 'ROLE', ENUM_VALUE: 'ADMIN', DISPLAY_TEXT: 'Quản trị', SORT_ORDER: 1 },
  { ENUM_GROUP: 'ROLE', ENUM_VALUE: 'OPERATOR', DISPLAY_TEXT: 'Vận hành', SORT_ORDER: 2 },
  { ENUM_GROUP: 'ROLE', ENUM_VALUE: 'ACCOUNTANT', DISPLAY_TEXT: 'Kế toán', SORT_ORDER: 3 },
  { ENUM_GROUP: 'ROLE', ENUM_VALUE: 'VIEWER', DISPLAY_TEXT: 'Xem chỉ', SORT_ORDER: 4 },
  { ENUM_GROUP: 'HO_SO_TYPE', ENUM_VALUE: 'HTX', DISPLAY_TEXT: 'Hợp tác xã', SORT_ORDER: 1 },
  { ENUM_GROUP: 'HO_SO_TYPE', ENUM_VALUE: 'XA_VIEN', DISPLAY_TEXT: 'Xã viên', SORT_ORDER: 2 },
  { ENUM_GROUP: 'HO_SO_TYPE', ENUM_VALUE: 'XE', DISPLAY_TEXT: 'Xe', SORT_ORDER: 3 },
  { ENUM_GROUP: 'HO_SO_TYPE', ENUM_VALUE: 'TAI_XE', DISPLAY_TEXT: 'Tài xế', SORT_ORDER: 4 },
  { ENUM_GROUP: 'HO_SO_STATUS', ENUM_VALUE: 'NEW', SORT_ORDER: 1 },
  { ENUM_GROUP: 'HO_SO_STATUS', ENUM_VALUE: 'ACTIVE', SORT_ORDER: 2 },
  { ENUM_GROUP: 'HO_SO_STATUS', ENUM_VALUE: 'INACTIVE', SORT_ORDER: 3 },
  { ENUM_GROUP: 'HO_SO_STATUS', ENUM_VALUE: 'ARCHIVED', SORT_ORDER: 4 },
  { ENUM_GROUP: 'FILE_GROUP', ENUM_VALUE: 'CCCD', SORT_ORDER: 1 },
  { ENUM_GROUP: 'FILE_GROUP', ENUM_VALUE: 'GPLX', SORT_ORDER: 2 },
  { ENUM_GROUP: 'FILE_GROUP', ENUM_VALUE: 'DANG_KY_XE', SORT_ORDER: 3 },
  { ENUM_GROUP: 'FILE_GROUP', ENUM_VALUE: 'HOP_DONG', SORT_ORDER: 4 },
  { ENUM_GROUP: 'FILE_GROUP', ENUM_VALUE: 'KHAC', SORT_ORDER: 5 },
  { ENUM_GROUP: 'TASK_TYPE', ENUM_VALUE: 'GENERAL', SORT_ORDER: 1 },
  { ENUM_GROUP: 'TASK_TYPE', ENUM_VALUE: 'HO_SO', SORT_ORDER: 2 },
  { ENUM_GROUP: 'TASK_TYPE', ENUM_VALUE: 'FINANCE', SORT_ORDER: 3 },
  { ENUM_GROUP: 'TASK_TYPE', ENUM_VALUE: 'OPERATION', SORT_ORDER: 4 },
  { ENUM_GROUP: 'TASK_STATUS', ENUM_VALUE: 'NEW', SORT_ORDER: 1 },
  { ENUM_GROUP: 'TASK_STATUS', ENUM_VALUE: 'ASSIGNED', SORT_ORDER: 2 },
  { ENUM_GROUP: 'TASK_STATUS', ENUM_VALUE: 'IN_PROGRESS', SORT_ORDER: 3 },
  { ENUM_GROUP: 'TASK_STATUS', ENUM_VALUE: 'WAITING', SORT_ORDER: 4 },
  { ENUM_GROUP: 'TASK_STATUS', ENUM_VALUE: 'DONE', SORT_ORDER: 5 },
  { ENUM_GROUP: 'TASK_STATUS', ENUM_VALUE: 'CANCELLED', SORT_ORDER: 6 },
  { ENUM_GROUP: 'TASK_STATUS', ENUM_VALUE: 'ARCHIVED', SORT_ORDER: 7 },
  { ENUM_GROUP: 'TASK_PRIORITY', ENUM_VALUE: 'LOW', DISPLAY_TEXT: 'Thấp', SORT_ORDER: 1 },
  { ENUM_GROUP: 'TASK_PRIORITY', ENUM_VALUE: 'MEDIUM', DISPLAY_TEXT: 'Trung bình', SORT_ORDER: 2 },
  { ENUM_GROUP: 'TASK_PRIORITY', ENUM_VALUE: 'HIGH', DISPLAY_TEXT: 'Cao', SORT_ORDER: 3 },
  { ENUM_GROUP: 'TASK_PRIORITY', ENUM_VALUE: 'URGENT', DISPLAY_TEXT: 'Khẩn cấp', SORT_ORDER: 4 },
  { ENUM_GROUP: 'ATTACHMENT_TYPE', ENUM_VALUE: 'FILE', SORT_ORDER: 1 },
  { ENUM_GROUP: 'ATTACHMENT_TYPE', ENUM_VALUE: 'IMAGE', SORT_ORDER: 2 },
  { ENUM_GROUP: 'ATTACHMENT_TYPE', ENUM_VALUE: 'LINK', SORT_ORDER: 3 },
  { ENUM_GROUP: 'TASK_ATTACHMENT_TYPE', ENUM_VALUE: 'DRAFT', DISPLAY_TEXT: 'Bản nháp', SORT_ORDER: 1 },
  { ENUM_GROUP: 'TASK_ATTACHMENT_TYPE', ENUM_VALUE: 'RESULT', DISPLAY_TEXT: 'Kết quả', SORT_ORDER: 2 },
  { ENUM_GROUP: 'TASK_ATTACHMENT_TYPE', ENUM_VALUE: 'SOP', DISPLAY_TEXT: 'Quy trình', SORT_ORDER: 3 },
  { ENUM_GROUP: 'TASK_ATTACHMENT_TYPE', ENUM_VALUE: 'REFERENCE', DISPLAY_TEXT: 'Tham khảo', SORT_ORDER: 4 },
  { ENUM_GROUP: 'FINANCE_ATTACHMENT_TYPE', ENUM_VALUE: 'INVOICE', DISPLAY_TEXT: 'Hóa đơn', SORT_ORDER: 1 },
  { ENUM_GROUP: 'FINANCE_ATTACHMENT_TYPE', ENUM_VALUE: 'RECEIPT', DISPLAY_TEXT: 'Biên lai', SORT_ORDER: 2 },
  { ENUM_GROUP: 'FINANCE_ATTACHMENT_TYPE', ENUM_VALUE: 'CONTRACT', DISPLAY_TEXT: 'Hợp đồng', SORT_ORDER: 3 },
  { ENUM_GROUP: 'FINANCE_ATTACHMENT_TYPE', ENUM_VALUE: 'PROOF', DISPLAY_TEXT: 'Chứng minh', SORT_ORDER: 4 },
  { ENUM_GROUP: 'FINANCE_ATTACHMENT_TYPE', ENUM_VALUE: 'OTHER', DISPLAY_TEXT: 'Khác', SORT_ORDER: 5 },
  { ENUM_GROUP: 'UPDATE_TYPE', ENUM_VALUE: 'NOTE', DISPLAY_TEXT: 'Ghi chú', SORT_ORDER: 1 },
  { ENUM_GROUP: 'UPDATE_TYPE', ENUM_VALUE: 'QUESTION', DISPLAY_TEXT: 'Câu hỏi', SORT_ORDER: 2 },
  { ENUM_GROUP: 'UPDATE_TYPE', ENUM_VALUE: 'ANSWER', DISPLAY_TEXT: 'Trả lời', SORT_ORDER: 3 },
  { ENUM_GROUP: 'UPDATE_TYPE', ENUM_VALUE: 'STATUS_CHANGE', DISPLAY_TEXT: 'Đổi trạng thái', SORT_ORDER: 4 },
  { ENUM_GROUP: 'FINANCE_TYPE', ENUM_VALUE: 'INCOME', DISPLAY_TEXT: 'Thu', SORT_ORDER: 1 },
  { ENUM_GROUP: 'FINANCE_TYPE', ENUM_VALUE: 'EXPENSE', DISPLAY_TEXT: 'Chi', SORT_ORDER: 2 },
  { ENUM_GROUP: 'FINANCE_STATUS', ENUM_VALUE: 'NEW', SORT_ORDER: 1 },
  { ENUM_GROUP: 'FINANCE_STATUS', ENUM_VALUE: 'CONFIRMED', SORT_ORDER: 2 },
  { ENUM_GROUP: 'FINANCE_STATUS', ENUM_VALUE: 'CANCELLED', SORT_ORDER: 3 },
  { ENUM_GROUP: 'FINANCE_STATUS', ENUM_VALUE: 'ARCHIVED', SORT_ORDER: 4 },
  { ENUM_GROUP: 'FIN_CATEGORY', ENUM_VALUE: 'VAN_HANH', SORT_ORDER: 1 },
  { ENUM_GROUP: 'FIN_CATEGORY', ENUM_VALUE: 'NHIEN_LIEU', SORT_ORDER: 2 },
  { ENUM_GROUP: 'FIN_CATEGORY', ENUM_VALUE: 'SUA_CHUA', SORT_ORDER: 3 },
  { ENUM_GROUP: 'FIN_CATEGORY', ENUM_VALUE: 'LUONG', SORT_ORDER: 4 },
  { ENUM_GROUP: 'FIN_CATEGORY', ENUM_VALUE: 'THU_KHAC', SORT_ORDER: 5 },
  { ENUM_GROUP: 'FIN_CATEGORY', ENUM_VALUE: 'CHI_KHAC', SORT_ORDER: 6 },
  { ENUM_GROUP: 'PAYMENT_METHOD', ENUM_VALUE: 'CASH', DISPLAY_TEXT: 'Tiền mặt', SORT_ORDER: 1 },
  { ENUM_GROUP: 'PAYMENT_METHOD', ENUM_VALUE: 'BANK', DISPLAY_TEXT: 'Chuyển khoản', SORT_ORDER: 2 },
  { ENUM_GROUP: 'PAYMENT_METHOD', ENUM_VALUE: 'OTHER', DISPLAY_TEXT: 'Khác', SORT_ORDER: 3 },
  { ENUM_GROUP: 'MASTER_CODE_STATUS', ENUM_VALUE: 'ACTIVE', SORT_ORDER: 1 },
  { ENUM_GROUP: 'MASTER_CODE_STATUS', ENUM_VALUE: 'INACTIVE', SORT_ORDER: 2 },
  { ENUM_GROUP: 'MASTER_CODE_STATUS', ENUM_VALUE: 'ARCHIVED', SORT_ORDER: 3 },
  { ENUM_GROUP: 'USER_DIRECTORY_STATUS', ENUM_VALUE: 'ACTIVE', SORT_ORDER: 1 },
  { ENUM_GROUP: 'USER_DIRECTORY_STATUS', ENUM_VALUE: 'INACTIVE', SORT_ORDER: 2 },
  { ENUM_GROUP: 'USER_DIRECTORY_STATUS', ENUM_VALUE: 'ARCHIVED', SORT_ORDER: 3 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'NONE', SORT_ORDER: 1 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'HO_SO', SORT_ORDER: 2 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'FINANCE_TRANSACTION', SORT_ORDER: 3 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'TASK', SORT_ORDER: 4 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'UNIT', SORT_ORDER: 5 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'XA_VIEN', SORT_ORDER: 6 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'TAI_XE', SORT_ORDER: 7 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'PHUONG_TIEN', SORT_ORDER: 8 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'GPS', SORT_ORDER: 9 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'CAMERA', SORT_ORDER: 10 },
  { ENUM_GROUP: 'RELATED_ENTITY_TYPE', ENUM_VALUE: 'DON_VI', SORT_ORDER: 11 },
  { ENUM_GROUP: 'HO_SO_STATUS', ENUM_VALUE: 'IN_REVIEW', DISPLAY_TEXT: 'Đang duyệt', SORT_ORDER: 5 },
  { ENUM_GROUP: 'HO_SO_STATUS', ENUM_VALUE: 'EXPIRED', DISPLAY_TEXT: 'Hết hạn', SORT_ORDER: 6 },
  { ENUM_GROUP: 'HO_SO_STATUS', ENUM_VALUE: 'CLOSED', DISPLAY_TEXT: 'Đóng', SORT_ORDER: 7 },
  { ENUM_GROUP: 'PRIORITY', ENUM_VALUE: 'LOW', DISPLAY_TEXT: 'Thấp', SORT_ORDER: 1 },
  { ENUM_GROUP: 'PRIORITY', ENUM_VALUE: 'MEDIUM', DISPLAY_TEXT: 'Trung bình', SORT_ORDER: 2 },
  { ENUM_GROUP: 'PRIORITY', ENUM_VALUE: 'HIGH', DISPLAY_TEXT: 'Cao', SORT_ORDER: 3 },
  { ENUM_GROUP: 'PRIORITY', ENUM_VALUE: 'URGENT', DISPLAY_TEXT: 'Khẩn cấp', SORT_ORDER: 4 },
  { ENUM_GROUP: 'ID_TYPE', ENUM_VALUE: 'CCCD', SORT_ORDER: 1 },
  { ENUM_GROUP: 'ID_TYPE', ENUM_VALUE: 'CMND', SORT_ORDER: 2 },
  { ENUM_GROUP: 'ID_TYPE', ENUM_VALUE: 'PASSPORT', SORT_ORDER: 3 },
  { ENUM_GROUP: 'ID_TYPE', ENUM_VALUE: 'GPLX', SORT_ORDER: 4 },
  { ENUM_GROUP: 'ID_TYPE', ENUM_VALUE: 'MST', SORT_ORDER: 5 },
  { ENUM_GROUP: 'ID_TYPE', ENUM_VALUE: 'GIAY_DANG_KY_XE', SORT_ORDER: 6 },
  { ENUM_GROUP: 'ID_TYPE', ENUM_VALUE: 'KHAC', SORT_ORDER: 7 },
  { ENUM_GROUP: 'SOURCE_CHANNEL', ENUM_VALUE: 'DIRECT', SORT_ORDER: 1 },
  { ENUM_GROUP: 'SOURCE_CHANNEL', ENUM_VALUE: 'EMAIL', SORT_ORDER: 2 },
  { ENUM_GROUP: 'SOURCE_CHANNEL', ENUM_VALUE: 'FORM', SORT_ORDER: 3 },
  { ENUM_GROUP: 'SOURCE_CHANNEL', ENUM_VALUE: 'ZALO', SORT_ORDER: 4 },
  { ENUM_GROUP: 'SOURCE_CHANNEL', ENUM_VALUE: 'DRIVE', SORT_ORDER: 5 },
  { ENUM_GROUP: 'SOURCE_CHANNEL', ENUM_VALUE: 'IMPORT', SORT_ORDER: 6 },
  { ENUM_GROUP: 'SOURCE_CHANNEL', ENUM_VALUE: 'INTERNAL', SORT_ORDER: 7 },
  { ENUM_GROUP: 'FILE_TYPE', ENUM_VALUE: 'MAIN_DOC', SORT_ORDER: 1 },
  { ENUM_GROUP: 'FILE_TYPE', ENUM_VALUE: 'ATTACHMENT', SORT_ORDER: 2 },
  { ENUM_GROUP: 'FILE_TYPE', ENUM_VALUE: 'ID_CARD', SORT_ORDER: 3 },
  { ENUM_GROUP: 'FILE_TYPE', ENUM_VALUE: 'CONTRACT', SORT_ORDER: 4 },
  { ENUM_GROUP: 'FILE_TYPE', ENUM_VALUE: 'APPENDIX', SORT_ORDER: 5 },
  { ENUM_GROUP: 'FILE_TYPE', ENUM_VALUE: 'PHOTO', SORT_ORDER: 6 },
  { ENUM_GROUP: 'FILE_TYPE', ENUM_VALUE: 'LICENSE', SORT_ORDER: 7 },
  { ENUM_GROUP: 'FILE_TYPE', ENUM_VALUE: 'EVIDENCE', SORT_ORDER: 8 },
  { ENUM_GROUP: 'FILE_TYPE', ENUM_VALUE: 'OTHER', SORT_ORDER: 9 },
  { ENUM_GROUP: 'HO_SO_ACTION_TYPE', ENUM_VALUE: 'CREATE', SORT_ORDER: 1 },
  { ENUM_GROUP: 'HO_SO_ACTION_TYPE', ENUM_VALUE: 'UPDATE_INFO', SORT_ORDER: 2 },
  { ENUM_GROUP: 'HO_SO_ACTION_TYPE', ENUM_VALUE: 'CHANGE_STATUS', SORT_ORDER: 3 },
  { ENUM_GROUP: 'HO_SO_ACTION_TYPE', ENUM_VALUE: 'ADD_FILE', SORT_ORDER: 4 },
  { ENUM_GROUP: 'HO_SO_ACTION_TYPE', ENUM_VALUE: 'REMOVE_FILE', SORT_ORDER: 5 },
  { ENUM_GROUP: 'HO_SO_ACTION_TYPE', ENUM_VALUE: 'LINK_ENTITY', SORT_ORDER: 6 },
  { ENUM_GROUP: 'HO_SO_ACTION_TYPE', ENUM_VALUE: 'UNLINK_ENTITY', SORT_ORDER: 7 },
  { ENUM_GROUP: 'HO_SO_ACTION_TYPE', ENUM_VALUE: 'CLOSE', SORT_ORDER: 8 },
  { ENUM_GROUP: 'HO_SO_ACTION_TYPE', ENUM_VALUE: 'ARCHIVE', SORT_ORDER: 9 },
  { ENUM_GROUP: 'RECORD_STATUS', ENUM_VALUE: 'ACTIVE', SORT_ORDER: 1 },
  { ENUM_GROUP: 'RECORD_STATUS', ENUM_VALUE: 'INACTIVE', SORT_ORDER: 2 }
];

function seedEnumDictionary() {
  var result = buildStructuredBootstrapReport();
  result.code = 'ENUM_SEED';

  var ss = SpreadsheetApp.getActive();
  var sheet = ss.getSheetByName(CBV_CONFIG.SHEETS.ENUM_DICTIONARY);
  var created = false;
  if (!sheet) {
    sheet = ss.insertSheet(CBV_CONFIG.SHEETS.ENUM_DICTIONARY);
    created = true;
    result.data.createdSheets = [CBV_CONFIG.SHEETS.ENUM_DICTIONARY];
  }

  var lastCol = sheet.getLastColumn();
  var headers = lastCol > 0 ? sheet.getRange(1, 1, 1, lastCol).getValues()[0] : [];
  if (headers.length === 0 || headers.indexOf('ENUM_GROUP') === -1) {
    sheet.getRange(1, 1, 1, ENUM_DICTIONARY_HEADERS.length).setValues([ENUM_DICTIONARY_HEADERS]);
    headers = ENUM_DICTIONARY_HEADERS;
  }

  var lastRow = sheet.getLastRow();
  var existingKeys = [];
  if (lastRow >= 2) {
    var groupIdx = headers.indexOf('ENUM_GROUP');
    var valueIdx = headers.indexOf('ENUM_VALUE');
    if (groupIdx !== -1 && valueIdx !== -1) {
      var data = sheet.getRange(2, 1, lastRow, headers.length).getValues();
      existingKeys = data.map(function(r) { return String(r[groupIdx] || '') + '|' + String(r[valueIdx] || ''); });
    }
  }

  var added = 0;
  var now = cbvNow();
  var user = cbvUser();
  ENUM_SEED_SPEC.forEach(function(spec) {
    var key = spec.ENUM_GROUP + '|' + spec.ENUM_VALUE;
    if (existingKeys.indexOf(key) !== -1) return;
    var record = {
      ID: cbvMakeId('ENUM'),
      ENUM_GROUP: spec.ENUM_GROUP,
      ENUM_VALUE: spec.ENUM_VALUE,
      DISPLAY_TEXT: spec.DISPLAY_TEXT || '',
      SORT_ORDER: spec.SORT_ORDER != null ? spec.SORT_ORDER : '',
      IS_ACTIVE: true,
      NOTE: spec.NOTE || '',
      CREATED_AT: now,
      CREATED_BY: user,
      UPDATED_AT: now,
      UPDATED_BY: user
    };
    var out = headers.map(function(h) { return record[h] !== undefined ? record[h] : ''; });
    sheet.appendRow(out);
    existingKeys.push(key);
    added++;
  });

  result.data.warnings = result.data.warnings || [];
  if (added > 0) result.data.warnings.push('Added ' + added + ' enum rows');
  clearEnumCache();

  result.ok = true;
  result.message = 'Enum dictionary seeded';
  Logger.log('seedEnumDictionary: ' + JSON.stringify(result, null, 2));
  return result;
}
