/**
 * HO_SO module — enum group names (must exist in ENUM_DICTIONARY).
 */

var HOSO_ENUM_GROUPS = {
  HO_SO_STATUS: 'HO_SO_STATUS',
  PRIORITY: 'PRIORITY',
  RELATED_ENTITY_TYPE: 'RELATED_ENTITY_TYPE',
  ID_TYPE: 'ID_TYPE',
  SOURCE_CHANNEL: 'SOURCE_CHANNEL',
  FILE_TYPE: 'FILE_TYPE',
  HO_SO_ACTION_TYPE: 'HO_SO_ACTION_TYPE'
};

var HOSO_MASTER_GROUP_TYPE = 'HO_SO_TYPE';

/**
 * RELATED_TABLE values (uppercase) → CBV_CONFIG.SHEETS key for ref validation.
 * Extend when new link targets are supported.
 */
var HOSO_RELATION_TABLE_TO_SHEET = {
  TASK: 'TASK_MAIN',
  DON_VI: 'DON_VI',
  FINANCE_TRANSACTION: 'FINANCE_TRANSACTION',
  USER_DIRECTORY: 'USER_DIRECTORY',
  HO_SO: 'HO_SO_MASTER'
};

/** Allowed HO_SO_STATUS transitions (from -> [to]) */
var HOSO_STATUS_TRANSITIONS = {
  NEW: ['IN_REVIEW', 'ACTIVE', 'CLOSED', 'ARCHIVED'],
  IN_REVIEW: ['ACTIVE', 'CLOSED', 'ARCHIVED'],
  ACTIVE: ['EXPIRED', 'CLOSED', 'ARCHIVED', 'IN_REVIEW'],
  EXPIRED: ['ACTIVE', 'CLOSED', 'ARCHIVED'],
  CLOSED: ['ARCHIVED'],
  ARCHIVED: [],
  INACTIVE: ['ARCHIVED', 'CLOSED', 'ACTIVE', 'IN_REVIEW']
};
