/**
 * CBV Schema Manifest - Source of truth for sheet headers.
 * Aligned with 06_DATABASE/schema_manifest.json and _generated_schema/*.csv
 */
/**
 * CBV PRO final schema. HO_SO_MASTER: loại hồ sơ chỉ qua HO_SO_TYPE_ID (MASTER_CODE); không cột HO_SO_TYPE text.
 */
const CBV_SCHEMA_MANIFEST = {
  USER_DIRECTORY: [
    'ID', 'USER_CODE', 'FULL_NAME', 'DISPLAY_NAME', 'EMAIL', 'PHONE', 'ROLE', 'POSITION', 'STATUS', 'IS_SYSTEM', 'ALLOW_LOGIN', 'NOTE',
    'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED',
    'USER_ID', 'EMPLOYEE_CODE', 'DON_VI_ID', 'TEAM_ID', 'SUPERVISOR_ID', 'ROLE_CODE', 'USER_STATUS', 'WORKLOAD_LIMIT', 'ACTIVE_QUEUE_COUNT',
    'LAST_ACTIVE_AT', 'LAST_LOGIN_AT', 'IS_OPERATOR', 'IS_SUPERVISOR', 'IS_ADMIN', 'IS_RUNTIME_OWNER', 'IS_APPSHEET_ADMIN', 'APPSHEET_USER_ROLE',
    'DEFAULT_DASHBOARD', 'DEFAULT_QUEUE', 'CAN_ASSIGN', 'CAN_ESCALATE', 'CAN_RESOLVE', 'CAN_APPROVE'
  ],
  ADMIN_AUDIT_LOG: ['ID', 'AUDIT_TYPE', 'ENTITY_TYPE', 'ENTITY_ID', 'ACTION', 'BEFORE_JSON', 'AFTER_JSON', 'NOTE', 'ACTOR_ID', 'CREATED_AT'],
  MASTER_CODE: [
    'ID', 'MASTER_GROUP', 'CODE', 'NAME', 'DISPLAY_TEXT', 'STATUS', 'SORT_ORDER', 'IS_SYSTEM', 'ALLOW_EDIT', 'NOTE',
    'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED',
    'MASTER_ID', 'MASTER_LABEL', 'MODULE_CODE', 'DESCRIPTION', 'IS_ACTIVE', 'PARENT_CODE', 'RELATED_CODE', 'MASTER_CODE'
  ],
  
  // ===== DÁN VÀO CBV_SCHEMA_MANIFEST =====
 
  HO_SO_MASTER: [
    'ID',
    'CODE',
    'NAME',
    'HO_SO_CODE',
    'TITLE',
    'DISPLAY_NAME',
    'HO_SO_TYPE_ID',
    'STATUS',
    'DON_VI_ID',
    'OWNER_ID',
    'HTX_ID',
    'MANAGER_USER_ID',
    'RELATED_ENTITY_TYPE',
    'RELATED_ENTITY_ID',
    'FULL_NAME',
    'PHONE',
    'EMAIL',
    'ID_TYPE',
    'ID_NO',
    'DOB',
    'ADDRESS',
    'START_DATE',
    'END_DATE',
    'PRIORITY',
    'SOURCE_CHANNEL',
    'SUMMARY',
    'NOTE',
    'TAGS_TEXT',
    'CREATED_AT',
    'CREATED_BY',
    'UPDATED_AT',
    'UPDATED_BY',
    'IS_STARRED',
    'IS_PINNED',
    'IS_DELETED',
    'PENDING_ACTION'
  ],
 
  HO_SO_FILE: [
    // ── Đúng thứ tự Sheet ───────────────────────────────────────────
    'ID',           // col 1
    'HO_SO_ID',     // col 2
    'FILE_GROUP',   // col 3
    'FILE_NAME',    // col 4
    'FILE_URL',     // col 5
    'DRIVE_FILE_ID',// col 6
    'STATUS',       // col 7
    'NOTE',         // col 8
    'CREATED_AT',   // col 9  ← Sheet: CREATED_AT trước DOC_TYPE
    'CREATED_BY',   // col 10
    'DOC_TYPE',     // col 11
    'ISSUED_DATE',  // col 12
    'EXPIRY_DATE',  // col 13
    'DOC_NO',       // col 14  ← Sheet: DOC_NO ở cuối
  ],
 
  HO_SO_RELATION: [
    // ── Đúng thứ tự Sheet ───────────────────────────────────────────
    'ID',               // col 1
    'FROM_HO_SO_ID',    // col 2
    'TO_HO_SO_ID',      // col 3
    'RELATION_TYPE',    // col 4
    'START_DATE',       // col 5  ← Sheet: START_DATE trước STATUS
    'END_DATE',         // col 6
    'STATUS',           // col 7
    'NOTE',             // col 8
    'CREATED_AT',       // col 9
    'CREATED_BY',       // col 10
    'HO_SO_ID',         // col 11
    'RELATED_TABLE',    // col 12
    'RELATED_RECORD_ID',// col 13
    'UPDATED_AT',       // col 14  ← cols 14-16 chưa có trên Sheet
    'UPDATED_BY',       // col 15  ← ensureSchemas sẽ thêm
    'IS_DELETED',       // col 16  ← ensureSchemas sẽ thêm
  ],
 
// ===== HẾT PHẦN DÁN =====
  
  HO_SO_UPDATE_LOG: ['ID', 'HO_SO_ID', 'ACTION_TYPE', 'OLD_STATUS', 'NEW_STATUS', 'FIELD_CHANGED', 'OLD_VALUE', 'NEW_VALUE', 'NOTE', 'ACTOR_ID', 'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED'],
  DOC_REQUIREMENT: ['ID', 'HO_SO_TYPE', 'DOC_TYPE', 'IS_REQUIRED', 'VALID_MONTHS', 'DESCRIPTION', 'SORT_ORDER', 'IS_ACTIVE', 'NOTE', 'CREATED_AT', 'CREATED_BY'],
  DON_VI: [
    'ID', 'DON_VI_TYPE', 'CODE', 'NAME', 'DISPLAY_TEXT', 'SHORT_NAME', 'PARENT_ID', 'STATUS', 'SORT_ORDER', 'MANAGER_USER_ID', 'EMAIL', 'PHONE', 'ADDRESS', 'NOTE',
    'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED',
    'DON_VI_ID', 'DON_VI_CODE', 'DON_VI_NAME', 'PARENT_DON_VI_ID', 'TEAM_TYPE', 'LEVEL', 'QUEUE_OWNER', 'DEFAULT_SUPERVISOR_ID', 'DEFAULT_ASSIGN_ROLE',
    'WORKLOAD_LIMIT', 'ESCALATION_TEAM', 'ESCALATION_EMAIL', 'OWNER_USER_ID', 'RUNTIME_OWNER_ID', 'DON_VI_STATUS', 'IS_ACTIVE'
  ],
  TASK_MAIN: [
    'ID', 'TASK_CODE', 'TITLE', 'DESCRIPTION', 'TASK_TYPE_ID',
    'STATUS', 'PRIORITY', 'DON_VI_ID', 'OWNER_ID', 'REPORTER_ID', 'SHARED_WITH',
    'IS_PRIVATE',
    'START_DATE', 'DUE_DATE', 'DONE_AT', 'PROGRESS_PERCENT', 'RESULT_SUMMARY',
    'RELATED_ENTITY_TYPE', 'RELATED_ENTITY_ID',
    'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY',
    'IS_STARRED', 'IS_PINNED', 'IS_DELETED', 'PENDING_ACTION'
  ],
  TASK_CHECKLIST: [
    'ID', 'TASK_ID', 'ITEM_NO', 'TITLE', 'IS_REQUIRED', 'IS_DONE', 'DONE_AT', 'DONE_BY', 'NOTE',
    'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED',
    'SOURCE', 'SCHEMA_VERSION', 'IS_ARCHIVED',
  ],
  CHECKLIST_FEEDBACK: [
    'FEEDBACK_ID', 'CHECKLIST_ITEM_ID', 'TASK_ID', 'MESSAGE', 'AUTHOR', 'CREATED_AT', 'SOURCE', 'SCHEMA_VERSION',
  ],
  CHECKLIST_ATTACHMENTS: [
    'ATTACHMENT_ID', 'CHECKLIST_ITEM_ID', 'TASK_ID', 'FILE_NAME', 'DRIVE_FILE_ID', 'DRIVE_URL',
    'MIME_TYPE', 'SIZE', 'SOURCE', 'CREATED_BY', 'CREATED_AT', 'SCHEMA_VERSION',
  ],
  CHECKLIST_LINKS: [
    'LINK_ID', 'CHECKLIST_ITEM_ID', 'TASK_ID', 'LABEL', 'URL', 'TYPE', 'DESCRIPTION',
    'SOURCE', 'CREATED_BY', 'CREATED_AT', 'SCHEMA_VERSION',
  ],
  CHECKLIST_HISTORY: [
    'HISTORY_ID', 'CHECKLIST_ITEM_ID', 'TASK_ID', 'EVENT_TYPE', 'MESSAGE', 'ACTOR', 'CREATED_AT',
    'SOURCE', 'REF_ID', 'REF_TYPE', 'METADATA_JSON', 'SCHEMA_VERSION',
  ],
  CHECKLIST_TEMPLATES: [
    'TEMPLATE_ID', 'NAME', 'DESCRIPTION', 'CATEGORY', 'VERSION', 'IS_ACTIVE',
    'CREATED_BY', 'CREATED_AT', 'UPDATED_AT', 'SCHEMA_VERSION',
  ],
  CHECKLIST_TEMPLATE_ITEMS: [
    'TEMPLATE_ITEM_ID', 'TEMPLATE_ID', 'TITLE', 'NOTE', 'SORT_ORDER', 'DEFAULT_STATUS',
    'REQUIRED', 'TAGS_JSON', 'SCHEMA_VERSION',
  ],
  CHECKLIST_LAYOUT_STATE: [
    'LAYOUT_STATE_ID', 'TASK_ID', 'CHECKLIST_ITEM_ID', 'EXPANDED', 'LAST_OPENED_AT', 'UPDATED_AT',
    'SOURCE', 'SCHEMA_VERSION',
  ],
  TASK_UPDATE_LOG: ['ID', 'TASK_ID', 'UPDATE_TYPE', 'ACTION', 'ACTOR_ID', 'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED'],
  TASK_ATTACHMENT: [
    'ID', 'TASK_ID', 'SOURCE_MODE', 'ATTACHMENT_TYPE', 'TITLE',
    'FILE_NAME', 'UPLOAD_FILE', 'FILE_URL', 'DRIVE_FILE_ID',
    'FILE_EXT', 'LINK_DOMAIN', 'SORT_ORDER', 'STATUS', 'NOTE',
    'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED'
  ],
  FINANCE_ATTACHMENT: ['ID', 'FINANCE_ID', 'ATTACHMENT_TYPE', 'TITLE', 'FILE_NAME', 'FILE_URL', 'DRIVE_FILE_ID', 'NOTE', 'CREATED_AT', 'CREATED_BY'],
  FINANCE_TRANSACTION: ['ID', 'TRANS_CODE', 'TRANS_DATE', 'TRANS_TYPE', 'STATUS', 'CATEGORY', 'AMOUNT', 'DON_VI_ID', 'COUNTERPARTY', 'PAYMENT_METHOD', 'REFERENCE_NO', 'RELATED_ENTITY_TYPE', 'RELATED_ENTITY_ID', 'DESCRIPTION', 'EVIDENCE_URL', 'CONFIRMED_AT', 'CONFIRMED_BY', 'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED', 'IS_STARRED', 'IS_PINNED'],
  FINANCE_LOG: ['ID', 'FIN_ID', 'ACTION', 'BEFORE_JSON', 'AFTER_JSON', 'NOTE', 'ACTOR_ID', 'CREATED_AT'],

  HOME_ALERT: [
    'ALERT_ID',
    'ALERT_CODE',
    'ALERT_TYPE',
    'SEVERITY',
    'PRIORITY_SCORE',
    'TITLE',
    'MESSAGE',
    'MODULE_CODE',
    'RELATED_ENTITY_TYPE',
    'RELATED_ENTITY_ID',
    'RELATED_RECORD_URL',
    'ACTION_LABEL',
    'ACTION_TYPE',
    'ACTION_PAYLOAD_JSON',
    'STATUS',
    'IS_ACTIVE',
    'IS_RESOLVED',
    'CREATED_AT',
    'UPDATED_AT',
    'DUE_AT',
    'ASSIGNED_TO',
    'SORT_KEY',
    'DISPLAY_GROUP',
    'BADGE_TEXT',
    'BADGE_COLOR',
    'TRACE_ID',
    'SOURCE_HASH',
    'RESOLVED_AT',
    'RESOLVED_BY',
    'NOTE',
    'ACKNOWLEDGED_AT',
    'ACKNOWLEDGED_BY',
    'STATE_CHANGED_AT',
    'STATE_CHANGED_BY',
    'ESCALATED_AT',
    'EXPIRES_AT',
    'AUTO_CLEARED_AT',
    'AUTO_CLEARED_BY',
    'LAST_ACTION',
    'DISPLAY_TITLE',
    'DISPLAY_SUBTITLE',
    'DISPLAY_STATUS',
    'DISPLAY_BADGE',
    'DISPLAY_ICON',
    'DISPLAY_COLOR',
    'DISPLAY_ACTION_TEXT',
    'DISPLAY_PRIORITY_LABEL',
    'DISPLAY_TIME_AGO',
    'DISPLAY_ASSIGNEE',
    'DISPLAY_SUMMARY',
    'DISPLAY_FOOTER',
    'CARD_GROUP',
    'CARD_SORT',
    'CARD_LAYOUT',
    'UX_VISIBLE',
    'UX_GROUP_ORDER',
    'UX_ACTION_HINT',
    'DESKTOP_TITLE',
    'DESKTOP_SUBTITLE',
    'DESKTOP_PRIMARY_LINE',
    'DESKTOP_SECONDARY_LINE',
    'DESKTOP_META_LINE',
    'DESKTOP_ACTION_LINE',
    'DESKTOP_DETAIL_TITLE',
    'DESKTOP_DETAIL_SUMMARY',
    'DESKTOP_DETAIL_CONTEXT',
    'DESKTOP_DETAIL_NEXT_ACTION',
    'DESKTOP_DETAIL_DEBUG_VISIBLE',
    'DESKTOP_GROUP',
    'DESKTOP_SORT',
    'DESKTOP_IS_OPERATOR_VIEW',
    'ATTENTION_LEVEL',
    'ATTENTION_LABEL',
    'ATTENTION_ICON',
    'ATTENTION_COLOR',
    'ATTENTION_REASON',
    'ACTION_FOCUS',
    'ACTION_HINT',
    'ACTION_PRIORITY',
    'OWNER_LABEL',
    'OWNER_QUEUE',
    'OPERATOR_PRIMARY_TEXT',
    'OPERATOR_SECONDARY_TEXT',
    'OPERATOR_META_TEXT',
    'OPERATOR_NEXT_ACTION',
    'OPERATOR_HIDE_SORT_KEYS',
    'ASSIGNMENT_STATUS',
    'ASSIGNMENT_QUEUE',
    'ASSIGNED_TO_LABEL',
    'ASSIGNED_TEAM',
    'ASSIGNED_TEAM_LABEL',
    'ASSIGNED_BY',
    'ASSIGNMENT_NOTE',
    'CLAIMED_AT',
    'CLAIMED_BY',
    'LAST_OPERATOR_ACTION',
    'LAST_OPERATOR_ACTION_AT',
    'LAST_OPERATOR_ACTION_BY',
    'ESCALATE_AFTER_AT',
    'IS_STUCK',
    'STUCK_REASON',
    'IS_BLOCKED',
    'BLOCKED_REASON',
    'QUEUE_GROUP',
    'QUEUE_LABEL',
    'QUEUE_SORT',
    'WORKLOAD_KEY',
    'OPERATOR_DASHBOARD_GROUP',
    'OPERATOR_DASHBOARD_SORT',
    'SLA_POLICY',
    'SLA_TARGET_MINUTES',
    'SLA_DUE_AT',
    'SLA_STATUS',
    'SLA_BREACH_LEVEL',
    'SLA_ELAPSED_MINUTES',
    'SLA_LAST_CHECKED_AT',
    'SLA_NEXT_REVIEW_AT',
    'ESCALATION_LEVEL',
    'ESCALATION_STATUS',
    'ESCALATION_REASON',
    'ESCALATED_BY',
    'ESCALATED_TO',
    'LAST_ESCALATION_CHECK_AT',
    'ESCALATION_NEXT_ACTION',
    'ESCALATION_TRACE_ID'
  ],

  HOME_ALERT_SLA_POLICY: [
    'POLICY_ID',
    'POLICY_CODE',
    'ALERT_CODE',
    'ALERT_TYPE',
    'MODULE_CODE',
    'SEVERITY',
    'SLA_POLICY',
    'TARGET_MINUTES',
    'DUE_SOON_MINUTES',
    'BREACH_LEVEL_1_MINUTES',
    'BREACH_LEVEL_2_MINUTES',
    'ESCALATE_AFTER_MINUTES',
    'ESCALATE_TO_TEAM',
    'ESCALATE_TO_USER',
    'PRIORITY_WEIGHT',
    'ACTIVE',
    'SORT_ORDER',
    'NOTE',
    'CREATED_AT',
    'CREATED_BY',
    'UPDATED_AT',
    'UPDATED_BY',
    'IS_DELETED'
  ],

  HOME_ALERT_SLA_METRICS: [
    'METRIC_ID',
    'METRIC_DATE',
    'METRIC_SCOPE',
    'MODULE_CODE',
    'ALERT_CODE',
    'POLICY_CODE',
    'ACTIVE_COUNT',
    'ON_TRACK_COUNT',
    'DUE_SOON_COUNT',
    'OVERDUE_COUNT',
    'BREACHED_COUNT',
    'ESCALATED_COUNT',
    'STUCK_COUNT',
    'BLOCKED_COUNT',
    'AVG_ELAPSED_MINUTES',
    'MAX_ELAPSED_MINUTES',
    'OPERATOR_OVERLOAD_COUNT',
    'SUMMARY_JSON',
    'LAST_REFRESH_AT',
    'TRACE_ID'
  ],

  HOME_ALERT_AUTOMATION_CONFIG: [
    'CONFIG_ID',
    'AUTOMATION_CODE',
    'AUTOMATION_TYPE',
    'FUNCTION_NAME',
    'ENABLED',
    'SAFE_MODE',
    'FREQUENCY_MINUTES',
    'SCHEDULE_LABEL',
    'LAST_RUN_AT',
    'LAST_STATUS',
    'LAST_TRACE_ID',
    'LAST_ERROR',
    'RUN_COUNT',
    'MAX_RUNTIME_SECONDS',
    'ALLOW_WRITE',
    'ALLOW_NOTIFICATION',
    'ALLOW_TRIGGER_INSTALL',
    'NOTE',
    'CREATED_AT',
    'CREATED_BY',
    'UPDATED_AT',
    'UPDATED_BY',
    'IS_DELETED'
  ],

  HOME_ALERT_AUTOMATION_RUN_LOG: [
    'RUN_ID',
    'AUTOMATION_CODE',
    'FUNCTION_NAME',
    'STARTED_AT',
    'FINISHED_AT',
    'DURATION_MS',
    'STATUS',
    'SEVERITY',
    'TRACE_ID',
    'INPUT_JSON',
    'OUTPUT_JSON',
    'ERROR_MESSAGE',
    'SAFE_MODE',
    'ALLOW_WRITE',
    'RUN_BY',
    'CREATED_AT'
  ],

  HOME_ALERT_DAILY_SNAPSHOT: [
    'SNAPSHOT_ID',
    'SNAPSHOT_DATE',
    'ACTIVE_COUNT',
    'DUE_SOON_COUNT',
    'OVERDUE_COUNT',
    'BREACHED_COUNT',
    'ESCALATED_COUNT',
    'STUCK_COUNT',
    'BLOCKED_COUNT',
    'WAITING_COUNT',
    'UNASSIGNED_COUNT',
    'OPERATOR_OVERLOAD_COUNT',
    'TOP_ALERT_CODES_JSON',
    'TOP_OPERATORS_JSON',
    'SUMMARY_TEXT',
    'RECOMMENDED_ACTIONS_TEXT',
    'TRACE_ID',
    'CREATED_AT',
    'CREATED_BY'
  ],

  HOME_ALERT_WORKLOAD: [
    'WORKLOAD_ID',
    'OPERATOR_ID',
    'OPERATOR_LABEL',
    'TEAM_ID',
    'TEAM_LABEL',
    'ACTIVE_ALERT_COUNT',
    'UNASSIGNED_COUNT',
    'OVERDUE_COUNT',
    'ESCALATED_COUNT',
    'BLOCKED_COUNT',
    'WAITING_COUNT',
    'LAST_REFRESH_AT',
    'TRACE_ID'
  ],

  ENUM_DICTIONARY: [
    'ID', 'ENUM_GROUP', 'ENUM_VALUE', 'DISPLAY_TEXT', 'SORT_ORDER', 'IS_ACTIVE', 'NOTE',
    'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY',
    'IS_DELETED', 'ENUM_CODE', 'ENUM_LABEL', 'ENUM_DESCRIPTION', 'COLOR_CODE', 'ICON', 'IS_SYSTEM', 'PARENT_ENUM_CODE'
  ],

  TEAM_DIRECTORY: [
    'TEAM_ID', 'TEAM_CODE', 'TEAM_NAME', 'DON_VI_ID', 'SUPERVISOR_ID', 'TEAM_TYPE', 'DEFAULT_QUEUE', 'WORKLOAD_LIMIT',
    'ESCALATION_TEAM', 'STATUS', 'NOTE', 'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED'
  ],

  ROLE_PERMISSION_MATRIX: [
    'PERMISSION_ID', 'ROLE_CODE', 'ACTION_CODE', 'MODULE_CODE', 'RESOURCE_TYPE', 'CAN_VIEW', 'CAN_CREATE', 'CAN_EDIT', 'CAN_EXECUTE',
    'CAN_APPROVE', 'CAN_ASSIGN', 'CAN_ESCALATE', 'CAN_RESOLVE', 'STATUS', 'NOTE', 'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED'
  ],

  FEATURE_FLAG: [
    'FEATURE_ID', 'FEATURE_CODE', 'MODULE_CODE', 'FEATURE_NAME', 'ENABLED', 'STATUS', 'ROLLOUT_SCOPE', 'OWNER_USER_ID', 'NOTE',
    'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED'
  ],

  SYSTEM_REGISTRY: [
    'REGISTRY_ID', 'REGISTRY_TYPE', 'REGISTRY_CODE', 'MODULE_CODE', 'RESOURCE_TYPE', 'RESOURCE_NAME', 'RESOURCE_REF', 'STATUS',
    'OWNER_USER_ID', 'NOTE', 'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'IS_DELETED'
  ],

  /** Phase 85 — CBV Unified UI Contract (AppSheet + WebApp metadata layer) */
  CBV_UI_CONTRACT: [
    'UI_CONTRACT_ID',
    'SCREEN_CODE',
    'SCREEN_NAME',
    'MODULE_CODE',
    'DOMAIN_CODE',
    'USER_ROLE',
    'TEAM_CODE',
    'CHANNEL',
    'SCREEN_TYPE',
    'DATA_SOURCE_SHEET',
    'DATA_SOURCE_VIEW',
    'PRIMARY_KEY_FIELD',
    'PRIMARY_TEXT_FIELD',
    'SECONDARY_TEXT_FIELD',
    'META_TEXT_FIELD',
    'NEXT_ACTION_FIELD',
    'GROUP_BY_FIELD',
    'SORT_BY_FIELD',
    'SORT_DIRECTION',
    'WEBAPP_ROUTE',
    'APPSHEET_VIEW',
    'APPSHEET_DEEPLINK_EXPR',
    'ALLOWED_ACTIONS_JSON',
    'PERMISSION_RULE_CODE',
    'SECURITY_FILTER_HINT',
    'SLA_BADGE_FIELD',
    'STATUS_FIELD',
    'PRIORITY_FIELD',
    'IS_ENABLED',
    'IS_PILOT_READY',
    'DISPLAY_ORDER',
    'NOTES',
    'CREATED_AT',
    'CREATED_BY',
    'UPDATED_AT',
    'UPDATED_BY',
    'CONTRACT_VERSION'
  ]
};

/** SYSTEM_HEALTH_LOG sheet name - audit run summaries */
var SYSTEM_HEALTH_LOG_SHEET = 'SYSTEM_HEALTH_LOG';

/** SYSTEM_HEALTH_LOG column headers */
var SYSTEM_HEALTH_LOG_HEADERS = [
  'RUN_ID', 'RUN_AT', 'SYSTEM_HEALTH', 'BOOTSTRAP_SAFE', 'APPSHEET_READY',
  'CRITICAL_COUNT', 'HIGH_COUNT', 'MEDIUM_COUNT', 'LOW_COUNT', 'INFO_COUNT',
  'SCHEMA_UPDATED', 'APPENDED_COLUMNS_COUNT', 'MUST_FIX_NOW', 'WARNINGS', 'SUMMARY_JSON'
];

/** @returns {string[]} Required sheet names in canonical order */
function getRequiredSheetNames() {
  return Object.keys(CBV_SCHEMA_MANIFEST);
}

/** @returns {string[]} Headers for a sheet by name */
function getSchemaHeaders(sheetName) {
  const headers = CBV_SCHEMA_MANIFEST[sheetName];
  if (!headers) throw new Error('Unknown sheet: ' + sheetName);
  return headers;
}
