/**
 * PHASE_89 — WebApp Operational Workspace Skeleton (route registry)
 * READ_FIRST only.
 */

function CbvWebAppWorkspace_routeRegistry() {
  var routes = [
    {
      route: '/workspace',
      screenCode: 'HOME_WORKSPACE',
      title: 'Workspace',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.HOME,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Home operational workspace (read-first).'
    },
    {
      route: '/workspace/role-home',
      screenCode: 'WORKSPACE_ROLE_HOME',
      title: 'Workspace — Role home',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.ROLE_HOME,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 01 — role-based landing (read-first).'
    },
    {
      route: '/workspace/today',
      screenCode: 'WORKSPACE_TODAY_OPS',
      title: 'Workspace — Today',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.TODAY_OPS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 01 — today operations dashboard (read-first aggregates).'
    },
    {
      route: '/workspace/workboard',
      screenCode: 'STAFF_WORKBOARD_WS',
      title: 'Workspace — Workboard',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_WORKBOARD,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 06 — staff production workboard (read-first).'
    },
    {
      route: '/workboard',
      screenCode: 'STAFF_WORKBOARD_ALIAS',
      title: 'Workboard',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_WORKBOARD,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias for Milestone 06 staff workboard.'
    },
    {
      route: '/workspace/workboard/tasks',
      screenCode: 'RF02_WORKBOARD_TASKS',
      title: 'Workboard — Tasks',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_TASKS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_02 — task list v1 (read-first).'
    },
    {
      route: '/workboard/tasks',
      screenCode: 'RF02_WORKBOARD_TASKS_ALIAS',
      title: 'Workboard tasks',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_TASKS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_02 task list.'
    },
    {
      route: '/workspace/workboard/task-detail',
      screenCode: 'RF02_WORKBOARD_TASK_DETAIL',
      title: 'Workboard — Task detail',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_TASK_DETAIL,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_02 — task detail + timeline read v1.'
    },
    {
      route: '/workboard/task-detail',
      screenCode: 'RF02_WORKBOARD_TASK_DETAIL_ALIAS',
      title: 'Task detail',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_TASK_DETAIL,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_02 task detail.'
    },
    {
      route: '/workspace/workboard/search',
      screenCode: 'RF02_WORKBOARD_SEARCH',
      title: 'Workboard — Search',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_SEARCH,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_02 — unified search stub v1.'
    },
    {
      route: '/workboard/search',
      screenCode: 'RF02_WORKBOARD_SEARCH_ALIAS',
      title: 'Search',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_SEARCH,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_02 search.'
    },
    {
      route: '/workspace/workboard/notifications',
      screenCode: 'RF02_WORKBOARD_NOTIFICATIONS',
      title: 'Workboard — Notifications',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_NOTIFICATIONS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_02 — notification center stub v1.'
    },
    {
      route: '/workboard/notifications',
      screenCode: 'RF02_WORKBOARD_NOTIFICATIONS_ALIAS',
      title: 'Notifications',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_NOTIFICATIONS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_02 notifications.'
    },
    {
      route: '/workspace/workboard/files',
      screenCode: 'RF02_WORKBOARD_FILES',
      title: 'Workboard — Files',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_FILES,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_02 — file runtime stub v1.'
    },
    {
      route: '/workboard/files',
      screenCode: 'RF02_WORKBOARD_FILES_ALIAS',
      title: 'Files',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF02_WORKBOARD_FILES,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_02 files.'
    },
    {
      route: '/workspace/coordination',
      screenCode: 'RF03_COORDINATION_HOME',
      title: 'Coordination',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_HOME,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_03 — coordination home (manager or queue by role).'
    },
    {
      route: '/workboard/coordination',
      screenCode: 'RF03_COORDINATION_HOME_ALIAS',
      title: 'Coordination',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_HOME,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_03 coordination home.'
    },
    {
      route: '/workspace/coordination/manager',
      screenCode: 'RF03_COORDINATION_MANAGER',
      title: 'Coordination — Manager',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_MANAGER,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_03 — manager coordination workboard.'
    },
    {
      route: '/workspace/coordination/queue',
      screenCode: 'RF03_COORDINATION_QUEUE',
      title: 'Coordination — Queue',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_QUEUE,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_03 — queue runtime v1.'
    },
    {
      route: '/workboard/queue',
      screenCode: 'RF03_COORDINATION_QUEUE_ALIAS',
      title: 'Queue',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_QUEUE,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_03 queue.'
    },
    {
      route: '/workspace/coordination/overdue',
      screenCode: 'RF03_COORDINATION_OVERDUE',
      title: 'Coordination — Overdue',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_OVERDUE,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_03 — overdue runtime v1.'
    },
    {
      route: '/workboard/overdue',
      screenCode: 'RF03_COORDINATION_OVERDUE_ALIAS',
      title: 'Overdue',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_OVERDUE,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_03 overdue.'
    },
    {
      route: '/workspace/coordination/workload',
      screenCode: 'RF03_COORDINATION_WORKLOAD',
      title: 'Coordination — Workload',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_WORKLOAD,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_03 — staff workload v1.'
    },
    {
      route: '/workboard/workload',
      screenCode: 'RF03_COORDINATION_WORKLOAD_ALIAS',
      title: 'Workload',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_WORKLOAD,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_03 workload.'
    },
    {
      route: '/workspace/coordination/assignment',
      screenCode: 'RF03_COORDINATION_ASSIGNMENT',
      title: 'Coordination — Assignment',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_ASSIGNMENT,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_03 — assignment runtime v1 (execution locked).'
    },
    {
      route: '/workboard/assignment',
      screenCode: 'RF03_COORDINATION_ASSIGNMENT_ALIAS',
      title: 'Assignment',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF03_COORDINATION_ASSIGNMENT,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_03 assignment.'
    },
    {
      route: '/workspace/observation',
      screenCode: 'RF04_OBSERVATION_HOME',
      title: 'Observation Workboard',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_HOME,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_04 observation dashboard.'
    },
    {
      route: '/workspace/observation/health',
      screenCode: 'RF04_OBSERVATION_HEALTH',
      title: 'Runtime Health',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_HEALTH,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_04 runtime health.'
    },
    {
      route: '/workspace/observation/projections',
      screenCode: 'RF04_OBSERVATION_PROJECTIONS',
      title: 'Projection Health',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_PROJECTIONS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_04 projection health.'
    },
    {
      route: '/workspace/observation/queues',
      screenCode: 'RF04_OBSERVATION_QUEUES',
      title: 'Queue Health',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_QUEUES,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_04 queue health (RF_03).'
    },
    {
      route: '/workspace/observation/sync',
      screenCode: 'RF04_OBSERVATION_SYNC',
      title: 'Sync Health',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_SYNC,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_04 sync stub.'
    },
    {
      route: '/workspace/observation/audit',
      screenCode: 'RF04_OBSERVATION_AUDIT',
      title: 'Audit Feed',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_AUDIT,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_04 audit feed read-first.'
    },
    {
      route: '/workspace/observation/alerts',
      screenCode: 'RF04_OBSERVATION_ALERTS',
      title: 'Operational Alerts',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_ALERTS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'PHASE_RF_04 runtime alerts.'
    },
    {
      route: '/workboard/observation',
      screenCode: 'RF04_OBSERVATION_HOME_ALIAS',
      title: 'Observation',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_HOME,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_04 observation.'
    },
    {
      route: '/workboard/health',
      screenCode: 'RF04_OBSERVATION_HEALTH_ALIAS',
      title: 'Health',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_HEALTH,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_04 health.'
    },
    {
      route: '/workboard/audit',
      screenCode: 'RF04_OBSERVATION_AUDIT_ALIAS',
      title: 'Audit',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_AUDIT,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_04 audit.'
    },
    {
      route: '/workboard/alerts',
      screenCode: 'RF04_OBSERVATION_ALERTS_ALIAS',
      title: 'Alerts',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.RF04_OBSERVATION_ALERTS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias RF_04 alerts.'
    },
    {
      route: '/workspace/task-runtime',
      screenCode: 'INTERACTIVE_TASK_RUNTIME_WS',
      title: 'Workspace — Task runtime',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.INTERACTIVE_TASK_RUNTIME,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 09 — interactive task runtime (read-first; query taskId/rowKey/source/mode).'
    },
    {
      route: '/workspace/guided',
      screenCode: 'WORKSPACE_GUIDED_FLOW',
      title: 'Workspace — Guided',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.GUIDED_OPS,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 01 — guided SOP inline (read-first).'
    },
    {
      route: '/workspace/daily',
      screenCode: 'DAILY_OPERATION_HOME',
      title: 'Workspace — Daily',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.DAILY_OPERATION_HOME,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 03 — task-first daily home (HOME_ALERT adapter; read-first).'
    },
    {
      route: '/daily',
      screenCode: 'DAILY_OPERATION_HOME_ALIAS',
      title: 'Daily',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.DAILY_OPERATION_HOME,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias route for Milestone 03 daily home.'
    },
    {
      route: '/workspace/staff/tasks',
      screenCode: 'STAFF_TASK_INBOX',
      title: 'Workspace — Staff tasks',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_TASKS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 02 — staff task workspace (HOME_ALERT adapter; read-first).'
    },
    {
      route: '/staff/tasks',
      screenCode: 'STAFF_TASK_INBOX_ALIAS',
      title: 'Staff — Tasks',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_TASKS,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias route for staff inbox (same renderer as /workspace/staff/tasks).'
    },
    {
      route: '/workspace/staff/task-detail',
      screenCode: 'STAFF_TASK_DETAIL',
      title: 'Workspace — Task detail',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_TASK_DETAIL,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 02 — task detail + timeline (query taskId).'
    },
    {
      route: '/staff/task-detail',
      screenCode: 'STAFF_TASK_DETAIL_ALIAS',
      title: 'Staff — Task detail',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_TASK_DETAIL,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias route for task detail.'
    },
    {
      route: '/workspace/focus',
      screenCode: 'OPERATION_FOCUS_MODE',
      title: 'Workspace — Focus',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.FOCUS_MODE,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 04 — focus execution mode (read-first; optional taskId).'
    },
    {
      route: '/focus',
      screenCode: 'OPERATION_FOCUS_MODE_ALIAS',
      title: 'Focus',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.FOCUS_MODE,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias for Milestone 04 focus mode.'
    },
    {
      route: '/workspace/execution/task',
      screenCode: 'EXECUTION_TASK_DETAIL_WS',
      title: 'Workspace — Execution task',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_TASK_DETAIL,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 04 — alias to task detail execution cockpit (query taskId).'
    },
    {
      route: '/execution/task',
      screenCode: 'EXECUTION_TASK_DETAIL_ALIAS',
      title: 'Execution — Task',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_TASK_DETAIL,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias for execution task detail cockpit.'
    },
    {
      route: '/workspace/sop',
      screenCode: 'GUIDED_SOP_RUNTIME_WS',
      title: 'Workspace — Guided SOP',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.GUIDED_SOP_RUNTIME,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 05 — guided SOP runtime (read-first; optional taskId).'
    },
    {
      route: '/sop',
      screenCode: 'GUIDED_SOP_RUNTIME_ALIAS',
      title: 'Guided SOP',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.GUIDED_SOP_RUNTIME,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias for guided SOP runtime page.'
    },
    {
      route: '/workspace/staff/feedback',
      screenCode: 'STAFF_FEEDBACK',
      title: 'Workspace — Staff feedback',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_FEEDBACK,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Milestone 02 — staff feedback (safe sink when sheet exists).'
    },
    {
      route: '/staff/feedback',
      screenCode: 'STAFF_FEEDBACK_ALIAS',
      title: 'Staff — Feedback',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.STAFF_FEEDBACK,
      requiredRole: '*',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Alias route for staff feedback.'
    },
    {
      route: '/home-alert/my-queue',
      screenCode: 'HOME_ALERT_MY_QUEUE',
      title: 'HOME_ALERT — My Queue',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.QUEUE,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Read-first list; no write actions in Phase 89.'
    },
    {
      route: '/home-alert/sla',
      screenCode: 'HOME_ALERT_SLA_DASHBOARD',
      title: 'HOME_ALERT — SLA Dashboard',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.SLA,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: true,
      notes: 'Read-first SLA summary; placeholder if columns missing.'
    },
    {
      route: '/home-alert/timeline',
      screenCode: 'HOME_ALERT_TIMELINE',
      title: 'HOME_ALERT — Timeline',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.PLACEHOLDER,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: false,
      notes: 'Reserved placeholder (next phase).'
    },
    {
      route: '/home-alert/kanban',
      screenCode: 'HOME_ALERT_KANBAN',
      title: 'HOME_ALERT — Kanban',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.PLACEHOLDER,
      requiredRole: '*',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.HOME_ALERT,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: false,
      notes: 'Reserved placeholder (next phase).'
    },
    {
      route: '/runtime/health',
      screenCode: 'RUNTIME_HEALTH_DASHBOARD',
      title: 'Runtime — Health',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.PLACEHOLDER,
      requiredRole: 'ADMIN',
      dataSourceSheet: CBV_WEBAPP_WS_SHEETS.SYSTEM_HEALTH_LOG,
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: false,
      notes: 'Placeholder: runtime health surface (read-first).'
    },
    {
      route: '/reports',
      screenCode: 'REPORT_HANDOFF_VIEWER',
      title: 'Reports',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.PLACEHOLDER,
      requiredRole: 'ADMIN',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: false,
      notes: 'Placeholder: handoff/report viewer in WebApp later.'
    },
    {
      route: '/admin/reference',
      screenCode: 'ADMIN_REFERENCE_VIEWER',
      title: 'Admin — Reference',
      pageType: CBV_WEBAPP_WS_PAGE_TYPES.PLACEHOLDER,
      requiredRole: 'ADMIN',
      dataSourceSheet: '',
      mode: CBV_WEBAPP_WS_MODES.READ_FIRST,
      isEnabled: true,
      isPilotReady: false,
      notes: 'Placeholder: reference explorer in WebApp later.'
    }
  ];
  return routes;
}

function CbvWebAppWorkspace_routeByPath(route) {
  var rt = String(route || '').trim();
  if (!rt) return null;
  var all = CbvWebAppWorkspace_routeRegistry();
  for (var i = 0; i < all.length; i++) {
    if (String(all[i].route) === rt) return all[i];
  }
  return null;
}

