import type { ModuleRegistryEntry } from '../contracts';

/** Config-driven module registry — single source for Worker API */
export const MODULE_REGISTRY: ModuleRegistryEntry[] = [
  {
    moduleId: 'HOME',
    moduleName: 'Bàn điều phối',
    moduleGroup: 'OPERATIONS',
    moduleType: 'HOME',
    runtimeType: 'REACT',
    icon: '☀',
    description: 'Operational attention surface — việc cần xử lý hôm nay',
    primaryUrl: '/',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'STAFF', 'FINANCE', 'HO_SO', 'VIEW_ONLY'],
    permissionRequired: 'TASK_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 0,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Hôm nay',
  },
  {
    moduleId: 'TASK',
    moduleName: 'Việc vận hành',
    moduleGroup: 'OPERATIONS',
    moduleType: 'TASK',
    runtimeType: 'REACT',
    icon: '✓',
    description: 'React operational cognition runtime — TASK_MAIN',
    primaryUrl: '/tasks',
    mobileUrl: '',
    adminUrl: '',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'STAFF', 'FINANCE', 'HO_SO'],
    permissionRequired: 'TASK_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 1,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Việc của tôi',
  },
  {
    moduleId: 'TASK_APPSHEET',
    moduleName: 'Việc AppSheet',
    moduleGroup: 'OPERATIONS',
    moduleType: 'TASK',
    runtimeType: 'APPSHEET',
    icon: '📋',
    description: 'CBV_SSA_LAOCONG AppSheet — view TASK_MAIN',
    primaryUrl: '',
    openMode: 'NEW_TAB',
    roleRequired: ['ADMIN', 'MANAGER', 'STAFF', 'FINANCE', 'HO_SO'],
    permissionRequired: 'TASK_VIEW',
    isEnabled: true,
    isInternal: false,
    sortOrder: 12,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'TASK AppSheet',
    notes: 'CBV_APPSHEET_TASK_URL — vss có thể hết hạn, cập nhật từ AppSheet share link',
  },
  {
    moduleId: 'HO_SO',
    moduleName: 'Hồ sơ xã viên',
    moduleGroup: 'OPERATIONS',
    moduleType: 'HO_SO',
    runtimeType: 'REACT',
    icon: '📁',
    description: 'Danh sách hồ sơ React + AppSheet runtime',
    primaryUrl: '/hoso',
    mobileUrl: '',
    adminUrl: '',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'HO_SO', 'VIEW_ONLY'],
    permissionRequired: 'HO_SO_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 2,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Hồ sơ',
  },
  {
    moduleId: 'HO_SO_APPSHEET',
    moduleName: 'Hồ sơ AppSheet',
    moduleGroup: 'OPERATIONS',
    moduleType: 'HO_SO',
    runtimeType: 'APPSHEET',
    icon: '📱',
    description: 'AppSheet mobile/field runtime cho hồ sơ',
    primaryUrl: '',
    openMode: 'IFRAME',
    roleRequired: ['ADMIN', 'MANAGER', 'HO_SO'],
    permissionRequired: 'HO_SO_VIEW',
    isEnabled: true,
    isInternal: false,
    sortOrder: 3,
    status: 'ACTIVE',
    showInNav: false,
  },
  {
    moduleId: 'FINANCE',
    moduleName: 'Tài chính',
    moduleGroup: 'OPERATIONS',
    moduleType: 'FINANCE',
    runtimeType: 'REACT',
    icon: '₫',
    description: 'Finance runtime — React list + AppSheet ops',
    primaryUrl: '/finance',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'FINANCE', 'VIEW_ONLY'],
    permissionRequired: 'FINANCE_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 4,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Tài chính',
  },
  {
    moduleId: 'COORDINATION',
    moduleName: 'Phối hợp',
    moduleGroup: 'OPERATIONS',
    moduleType: 'COORDINATION',
    runtimeType: 'REACT',
    icon: '↔',
    description: 'Queue coordination và workload',
    primaryUrl: '/coordination',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER'],
    permissionRequired: 'COORDINATION_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 5,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Phối hợp',
  },
  {
    moduleId: 'OBSERVATION',
    moduleName: 'Quan sát runtime',
    moduleGroup: 'OPERATIONS',
    moduleType: 'OBSERVATION',
    runtimeType: 'NOCODB',
    icon: '◉',
    description: 'Runtime health, alerts, NocoDB observation',
    primaryUrl: '/observation',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'VIEW_ONLY'],
    permissionRequired: 'OBSERVATION_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 6,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Quan sát',
  },
  {
    moduleId: 'DOCUMENT',
    moduleName: 'Tài liệu',
    moduleGroup: 'REFERENCE',
    moduleType: 'DOCUMENT',
    runtimeType: 'EXTERNAL',
    icon: '📄',
    description: 'Google Drive / Outline document runtime',
    primaryUrl: 'https://drive.google.com',
    openMode: 'NEW_TAB',
    roleRequired: ['ADMIN', 'MANAGER', 'STAFF', 'FINANCE', 'HO_SO', 'VIEW_ONLY'],
    permissionRequired: 'TASK_VIEW',
    isEnabled: true,
    isInternal: false,
    sortOrder: 7,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Tài liệu',
  },
  {
    moduleId: 'SETTINGS',
    moduleName: 'Cấu hình mô-đun',
    moduleGroup: 'SETTINGS',
    moduleType: 'SETTINGS',
    runtimeType: 'REACT',
    icon: '▣',
    description: 'Module registry và runtime config',
    primaryUrl: '/plugins',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'VIEW_ONLY'],
    permissionRequired: 'PLUGIN_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 90,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Cấu hình',
  },
];
