"""
Extract CBV_SCHEMA_MANIFEST from 05_GAS_RUNTIME/90_BOOTSTRAP_SCHEMA.js
and merge runtime sheets documented in GAS but outside CBV_SCHEMA_MANIFEST:

- ENUM_DICTIONARY — columns from 01_ENUM_SEED.js (ENUM_DICTIONARY_HEADERS)
- SYSTEM_HEALTH_LOG — operational; columns from SYSTEM_HEALTH_LOG_HEADERS in bootstrap

Writes 06_DATABASE/schema_manifest.json (with _META, _operational_tables).

Usage (from repo root):
  python 99_TOOLS/sync_schema_manifest_from_bootstrap.py

Verify (manifest vs GAS + seed + operational + CBV_CONFIG coverage):
  python 99_TOOLS/sync_schema_manifest_from_bootstrap.py --verify
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

PACK_ROOT = Path(__file__).resolve().parents[1]
GAS_BOOTSTRAP = PACK_ROOT / "05_GAS_RUNTIME" / "90_BOOTSTRAP_SCHEMA.js"
ENUM_SEED = PACK_ROOT / "05_GAS_RUNTIME" / "01_ENUM_SEED.js"
CORE_CONFIG = PACK_ROOT / "05_GAS_RUNTIME" / "00_CORE_CONFIG.js"
MANIFEST = PACK_ROOT / "06_DATABASE" / "schema_manifest.json"

META = {
    "SOURCE_OF_TRUTH": "05_GAS_RUNTIME/90_BOOTSTRAP_SCHEMA.js",
    "DO_NOT_EDIT_MANUALLY": True,
    "EQUIVALENT_LINE_COMMENTS": [
        "// SOURCE OF TRUTH: 05_GAS_RUNTIME/90_BOOTSTRAP_SCHEMA.js",
        "// Do NOT edit this file manually.",
        "// Regenerate with: python 99_TOOLS/sync_schema_manifest_from_bootstrap.py "
        "(repo root), then python 99_TOOLS/export_sheet_schema_csv.py",
    ],
    "REGENERATE": (
        "Chạy: python 99_TOOLS/sync_schema_manifest_from_bootstrap.py "
        "(repo root). Sau đó: python 99_TOOLS/export_sheet_schema_csv.py"
    ),
    "COLUMN_NOTES_LEGACY": {
        "TASK_MAIN.RELATED_ENTITY_TYPE": (
            "ref → MASTER_CODE WHERE MASTER_GROUP = 'ENTITY_TYPE'"
        ),
        "FINANCE_TRANSACTION.RELATED_ENTITY_TYPE": (
            "ref → MASTER_CODE WHERE MASTER_GROUP = 'ENTITY_TYPE'"
        ),
    },
    "DEPRECATED_OR_REVIEW": [
        "Key gốc _COLUMN_NOTES (root) → gộp vào _META.COLUMN_NOTES_LEGACY.",
        "Phase 2: ENUM_DICTIONARY + SYSTEM_HEALTH_LOG khai báo từ "
        "01_ENUM_SEED.js / SYSTEM_HEALTH_LOG_HEADERS (ngoài CBV_SCHEMA_MANIFEST).",
    ],
    "PHASE2_CLASSIFICATION": {
        "ENUM_DICTIONARY": "schema — lookup / workflow enums (version control)",
        "DOC_REQUIREMENT": "schema — đã trong CBV_SCHEMA_MANIFEST",
        "FINANCE_ATTACHMENT": "schema — đã trong CBV_SCHEMA_MANIFEST",
        "FINANCE_LOG": "schema — audit trail giao dịch (append-only)",
        "SYSTEM_HEALTH_LOG": "operational — bootstrap/audit run summaries",
    },
}


def extract_cbv_schema_manifest(js_text: str) -> dict[str, list[str]]:
    js_nc = re.sub(r"//[^\n]*", "", js_text)
    start = js_nc.index("CBV_SCHEMA_MANIFEST")
    start = js_nc.index("{", start)
    depth = 0
    end = None
    for i in range(start, len(js_nc)):
        c = js_nc[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    if end is None:
        raise ValueError("Could not find closing brace for CBV_SCHEMA_MANIFEST")
    blob = js_nc[start:end]
    tables: dict[str, list[str]] = {}
    pos = 0
    while True:
        m = re.search(r"(\w+)\s*:\s*\[", blob[pos:])
        if not m:
            break
        name = m.group(1)
        bracket_start = pos + m.start() + m.group(0).rfind("[")
        d = 1
        j = bracket_start + 1
        while j < len(blob) and d:
            if blob[j] == "[":
                d += 1
            elif blob[j] == "]":
                d -= 1
            j += 1
        inner = blob[bracket_start + 1 : j - 1]
        cols = re.findall(r"'([\w_]+)'", inner)
        tables[name] = cols
        pos = j
    return tables


def extract_js_string_array(text: str, var_name: str) -> list[str]:
    m = re.search(rf"\b{re.escape(var_name)}\s*=\s*\[", text)
    if not m:
        raise ValueError(f"Array {var_name} not found")
    start_bracket = m.end() - 1
    d = 0
    i = start_bracket
    while i < len(text):
        if text[i] == "[":
            d += 1
        elif text[i] == "]":
            d -= 1
            if d == 0:
                inner = text[start_bracket + 1 : i]
                return re.findall(r"'([\w_]+)'", inner)
        i += 1
    raise ValueError(f"Unclosed array for {var_name}")


def extract_cbv_config_sheet_keys(config_text: str) -> list[str]:
    """Keys of CBV_CONFIG.SHEETS (left-hand names)."""
    m = re.search(r"SHEETS:\s*\{", config_text)
    if not m:
        raise ValueError("CBV_CONFIG.SHEETS not found")
    start = m.end() - 1
    depth = 0
    for i in range(start, len(config_text)):
        c = config_text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                blob = config_text[start + 1 : i]
                keys = re.findall(r"(\w+)\s*:", blob)
                return keys
    raise ValueError("Unclosed SHEETS block")


def build_schema_tables_with_enum(
    gas_tables: dict[str, list[str]], enum_columns: list[str]
) -> dict[str, list[str]]:
    """Insert ENUM_DICTIONARY after ADMIN_AUDIT_LOG (align 00_CORE_CONFIG order)."""
    out: dict[str, list[str]] = {}
    for k, v in gas_tables.items():
        if k == "MASTER_CODE":
            out["ENUM_DICTIONARY"] = enum_columns
        out[k] = v
    return out


def operational_system_health_log(columns: list[str]) -> dict:
    return {
        "source": (
            "05_GAS_RUNTIME/90_BOOTSTRAP_SCHEMA.js (SYSTEM_HEALTH_LOG_HEADERS); "
            "CBV_CONFIG.SHEETS.SYSTEM_HEALTH_LOG"
        ),
        "purpose": (
            "Operational: append-only summaries of bootstrap/audit runs "
            "(severity counts, AppSheet readiness, schema drift flags)."
        ),
        "has_is_deleted": False,
        "audit_fields": "RUN_AT; no UPDATED_AT/UPDATED_BY/IS_DELETED in header set",
        "columns": columns,
    }


def build_manifest_payload(
    schema_tables: dict[str, list[str]], operational: dict[str, dict]
) -> dict:
    table_order = list(schema_tables.keys())
    out: dict = {
        "_META": {
            **META,
            "TABLE_ORDER": table_order,
            "OPERATIONAL_TABLE_ORDER": list(operational.keys()),
        }
    }
    for k, v in schema_tables.items():
        out[k] = v
    out["_operational_tables"] = operational
    return out


def verify_manifest() -> int:
    bootstrap_js = GAS_BOOTSTRAP.read_text(encoding="utf-8")
    enum_js = ENUM_SEED.read_text(encoding="utf-8")
    cfg_js = CORE_CONFIG.read_text(encoding="utf-8")

    gas_tables = extract_cbv_schema_manifest(bootstrap_js)
    enum_cols = extract_js_string_array(enum_js, "ENUM_DICTIONARY_HEADERS")
    health_cols = extract_js_string_array(bootstrap_js, "SYSTEM_HEALTH_LOG_HEADERS")

    schema_tables = build_schema_with_enum(gas_tables, enum_cols)
    operational = {"SYSTEM_HEALTH_LOG": operational_system_health_log(health_cols)}
    expected = build_manifest_payload(schema_tables, operational)

    current = json.loads(MANIFEST.read_text(encoding="utf-8-sig"))

    # 1) Schema tables: must match
    for k, v in expected.items():
        if k in ("_META", "_operational_tables"):
            continue
        if not isinstance(v, list):
            continue
        if k not in current or current[k] != v:
            print("MISMATCH schema table:", k)
            print("  expected:", v)
            print("  current: ", current.get(k))
            return 1

    # 2) Operational
    if current.get("_operational_tables") != expected["_operational_tables"]:
        print("MISMATCH _operational_tables")
        return 1

    # 3) CBV_CONFIG: every sheet key covered by schema list or operational
    cfg_keys = set(extract_cbv_config_sheet_keys(cfg_js))
    schema_keys = {k for k, v in current.items() if isinstance(v, list)}
    op_keys = set(current.get("_operational_tables", {}))
    covered = schema_keys | op_keys
    missing = cfg_keys - covered
    if missing:
        print("CBV_CONFIG.SHEETS keys missing from manifest:", sorted(missing))
        return 1
    extra = covered - cfg_keys
    if extra - {"_META"}:
        # allow only ghost - actually _META not in covered
        stray = (schema_keys | op_keys) - cfg_keys
        if stray:
            print("WARN: manifest tables not in CBV_CONFIG.SHEETS:", sorted(stray))

    print("OK: manifest matches GAS + ENUM seed + operational; CBV_CONFIG covered.")
    return 0


def build_schema_with_enum(
    gas_tables: dict[str, list[str]], enum_columns: list[str]
) -> dict[str, list[str]]:
    return build_schema_tables_with_enum(gas_tables, enum_columns)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()

    bootstrap_js = GAS_BOOTSTRAP.read_text(encoding="utf-8")
    enum_js = ENUM_SEED.read_text(encoding="utf-8")

    gas_tables = extract_cbv_schema_manifest(bootstrap_js)
    enum_cols = extract_js_string_array(enum_js, "ENUM_DICTIONARY_HEADERS")
    health_cols = extract_js_string_array(bootstrap_js, "SYSTEM_HEALTH_LOG_HEADERS")

    schema_tables = build_schema_with_enum(gas_tables, enum_cols)
    operational = {"SYSTEM_HEALTH_LOG": operational_system_health_log(health_cols)}
    payload = build_manifest_payload(schema_tables, operational)

    if args.verify:
        return verify_manifest()

    MANIFEST.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print("Wrote", MANIFEST)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
