/**
 * PHASE_CHECKLIST_09 — Sheet schema manifest (mirrors GAS CBV_CHECKLIST_SHEET_SCHEMA_MANIFEST).
 */

export const CHECKLIST_SHEET_SCHEMA_VERSION = '1';

export type ChecklistSheetTabName =
  | 'TASK_CHECKLIST'
  | 'CHECKLIST_FEEDBACK'
  | 'CHECKLIST_ATTACHMENTS'
  | 'CHECKLIST_LINKS'
  | 'CHECKLIST_HISTORY'
  | 'CHECKLIST_TEMPLATES'
  | 'CHECKLIST_TEMPLATE_ITEMS'
  | 'CHECKLIST_LAYOUT_STATE';

export const CHECKLIST_SHEET_SCHEMA_MANIFEST: Record<ChecklistSheetTabName, readonly string[]> = {
  TASK_CHECKLIST: [
    'ID',
    'TASK_ID',
    'ITEM_NO',
    'TITLE',
    'IS_REQUIRED',
    'IS_DONE',
    'DONE_AT',
    'DONE_BY',
    'NOTE',
    'CREATED_AT',
    'CREATED_BY',
    'UPDATED_AT',
    'UPDATED_BY',
    'IS_DELETED',
    'SOURCE',
    'SCHEMA_VERSION',
    'IS_ARCHIVED',
  ],
  CHECKLIST_FEEDBACK: [
    'FEEDBACK_ID',
    'CHECKLIST_ITEM_ID',
    'TASK_ID',
    'MESSAGE',
    'AUTHOR',
    'CREATED_AT',
    'SOURCE',
    'SCHEMA_VERSION',
  ],
  CHECKLIST_ATTACHMENTS: [
    'ATTACHMENT_ID',
    'CHECKLIST_ITEM_ID',
    'TASK_ID',
    'FILE_NAME',
    'DRIVE_FILE_ID',
    'DRIVE_URL',
    'MIME_TYPE',
    'SIZE',
    'SOURCE',
    'CREATED_BY',
    'CREATED_AT',
    'SCHEMA_VERSION',
  ],
  CHECKLIST_LINKS: [
    'LINK_ID',
    'CHECKLIST_ITEM_ID',
    'TASK_ID',
    'LABEL',
    'URL',
    'TYPE',
    'DESCRIPTION',
    'SOURCE',
    'CREATED_BY',
    'CREATED_AT',
    'SCHEMA_VERSION',
  ],
  CHECKLIST_HISTORY: [
    'HISTORY_ID',
    'CHECKLIST_ITEM_ID',
    'TASK_ID',
    'EVENT_TYPE',
    'MESSAGE',
    'ACTOR',
    'CREATED_AT',
    'SOURCE',
    'REF_ID',
    'REF_TYPE',
    'METADATA_JSON',
    'SCHEMA_VERSION',
  ],
  CHECKLIST_TEMPLATES: [
    'TEMPLATE_ID',
    'NAME',
    'DESCRIPTION',
    'CATEGORY',
    'VERSION',
    'IS_ACTIVE',
    'CREATED_BY',
    'CREATED_AT',
    'UPDATED_AT',
    'SCHEMA_VERSION',
  ],
  CHECKLIST_TEMPLATE_ITEMS: [
    'TEMPLATE_ITEM_ID',
    'TEMPLATE_ID',
    'TITLE',
    'NOTE',
    'SORT_ORDER',
    'DEFAULT_STATUS',
    'REQUIRED',
    'TAGS_JSON',
    'SCHEMA_VERSION',
  ],
  CHECKLIST_LAYOUT_STATE: [
    'LAYOUT_STATE_ID',
    'TASK_ID',
    'CHECKLIST_ITEM_ID',
    'EXPANDED',
    'LAST_OPENED_AT',
    'UPDATED_AT',
    'SOURCE',
    'SCHEMA_VERSION',
  ],
} as const;

export const CHECKLIST_SHEET_LOGICAL_ROLES: Record<ChecklistSheetTabName, string> = {
  TASK_CHECKLIST: 'CHECKLIST_ITEMS',
  CHECKLIST_FEEDBACK: 'CHECKLIST_FEEDBACK',
  CHECKLIST_ATTACHMENTS: 'CHECKLIST_ATTACHMENTS',
  CHECKLIST_LINKS: 'CHECKLIST_LINKS',
  CHECKLIST_HISTORY: 'CHECKLIST_HISTORY',
  CHECKLIST_TEMPLATES: 'CHECKLIST_TEMPLATES',
  CHECKLIST_TEMPLATE_ITEMS: 'CHECKLIST_TEMPLATE_ITEMS',
  CHECKLIST_LAYOUT_STATE: 'CHECKLIST_LAYOUT_STATE',
};

export const CHECKLIST_APPEND_ONLY_SHEET_TABS: ChecklistSheetTabName[] = [
  'CHECKLIST_FEEDBACK',
  'CHECKLIST_HISTORY',
];

export const CHECKLIST_SHEET_TAB_NAMES = Object.keys(
  CHECKLIST_SHEET_SCHEMA_MANIFEST,
) as ChecklistSheetTabName[];
