import type { ModuleRegistryEntry } from '@/api/contracts';

/** Safe under Node/tsx static check runners where `import.meta.env` may be undefined. */
const viteEnv = import.meta?.env ?? ({} as ImportMeta['env']);

/** Local mirror — Worker `/api/modules` is source of truth when connected */
export const LOCAL_MODULE_REGISTRY: ModuleRegistryEntry[] = [
  {
    moduleId: 'HOME',
    moduleName: 'Bàn điều phối',
    moduleGroup: 'OPERATIONS',
    moduleType: 'HOME',
    runtimeType: 'REACT',
    icon: '☀',
    description: 'Operational attention surface',
    primaryUrl: '/home',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'STAFF', 'FINANCE', 'HO_SO', 'VIEW_ONLY'],
    permissionRequired: 'TASK_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 0,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Hôm nay',
  },
  {
    moduleId: 'TASK',
    moduleName: 'Việc vận hành',
    moduleGroup: 'OPERATIONS',
    moduleType: 'TASK',
    runtimeType: 'REACT',
    icon: '✓',
    description: 'React TASK runtime',
    primaryUrl: '/tasks',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'STAFF', 'FINANCE', 'HO_SO'],
    permissionRequired: 'TASK_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 1,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Việc của tôi',
  },
  {
    moduleId: 'TASK_APPSHEET',
    moduleName: 'Việc AppSheet',
    moduleGroup: 'OPERATIONS',
    moduleType: 'TASK',
    runtimeType: 'APPSHEET',
    icon: '📋',
    description: 'CBV_SSA_LAOCONG AppSheet — TASK_MAIN',
    primaryUrl: viteEnv.VITE_CBV_APPSHEET_TASK_URL?.trim() ?? '',
    openMode: 'NEW_TAB',
    roleRequired: ['ADMIN', 'MANAGER', 'STAFF', 'FINANCE', 'HO_SO'],
    permissionRequired: 'TASK_VIEW',
    isEnabled: Boolean(viteEnv.VITE_CBV_APPSHEET_TASK_URL?.trim()),
    isInternal: false,
    sortOrder: 12,
    status: viteEnv.VITE_CBV_APPSHEET_TASK_URL ? 'ACTIVE' : 'NOT_CONFIGURED',
    showInNav: true,
    navLabel: 'TASK AppSheet',
  },
  {
    moduleId: 'HO_SO',
    moduleName: 'Hồ sơ xã viên',
    moduleGroup: 'OPERATIONS',
    moduleType: 'HO_SO',
    runtimeType: 'REACT',
    icon: '📁',
    description: 'Hồ sơ React + AppSheet',
    primaryUrl: '/hoso',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'HO_SO', 'VIEW_ONLY'],
    permissionRequired: 'HO_SO_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 2,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Hồ sơ',
  },
  {
    moduleId: 'HO_SO_APPSHEET',
    moduleName: 'Hồ sơ AppSheet',
    moduleGroup: 'OPERATIONS',
    moduleType: 'HO_SO',
    runtimeType: 'APPSHEET',
    icon: '📱',
    description: 'AppSheet field runtime',
    primaryUrl: viteEnv.VITE_CBV_APPSHEET_HOSO_URL?.trim() ?? '',
    openMode: 'IFRAME',
    roleRequired: ['ADMIN', 'MANAGER', 'HO_SO'],
    permissionRequired: 'HO_SO_VIEW',
    isEnabled: Boolean(viteEnv.VITE_CBV_APPSHEET_HOSO_URL?.trim()),
    isInternal: false,
    sortOrder: 3,
    status: viteEnv.VITE_CBV_APPSHEET_HOSO_URL ? 'ACTIVE' : 'NOT_CONFIGURED',
    showInNav: false,
  },
  {
    moduleId: 'FINANCE',
    moduleName: 'Tài chính',
    moduleGroup: 'OPERATIONS',
    moduleType: 'FINANCE',
    runtimeType: 'REACT',
    icon: '₫',
    description: 'Finance runtime',
    primaryUrl: '/finance',
    mobileUrl: viteEnv.VITE_CBV_APPSHEET_FINANCE_URL?.trim(),
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'FINANCE', 'VIEW_ONLY'],
    permissionRequired: 'FINANCE_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 4,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Tài chính',
  },
  {
    moduleId: 'COORDINATION',
    moduleName: 'Phối hợp',
    moduleGroup: 'OPERATIONS',
    moduleType: 'COORDINATION',
    runtimeType: 'REACT',
    icon: '↔',
    description: 'Coordination queue',
    primaryUrl: '/coordination',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER'],
    permissionRequired: 'COORDINATION_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 5,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Phối hợp',
  },
  {
    moduleId: 'OBSERVATION',
    moduleName: 'Quan sát',
    moduleGroup: 'OPERATIONS',
    moduleType: 'OBSERVATION',
    runtimeType: 'NOCODB',
    icon: '◉',
    description: 'Runtime health & observation',
    primaryUrl: '/observation',
    mobileUrl: viteEnv.VITE_CBV_NOCODB_URL?.trim(),
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'VIEW_ONLY'],
    permissionRequired: 'OBSERVATION_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 6,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Quan sát',
  },
  {
    moduleId: 'DOCUMENT',
    moduleName: 'Tài liệu',
    moduleGroup: 'REFERENCE',
    moduleType: 'DOCUMENT',
    runtimeType: 'EXTERNAL',
    icon: '📄',
    description: 'Drive / Outline',
    primaryUrl: 'https://drive.google.com',
    openMode: 'NEW_TAB',
    roleRequired: ['ADMIN', 'MANAGER', 'STAFF', 'FINANCE', 'HO_SO', 'VIEW_ONLY'],
    permissionRequired: 'TASK_VIEW',
    isEnabled: true,
    isInternal: false,
    sortOrder: 7,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Tài liệu',
  },
  {
    moduleId: 'SETTINGS',
    moduleName: 'Cấu hình',
    moduleGroup: 'SETTINGS',
    moduleType: 'SETTINGS',
    runtimeType: 'REACT',
    icon: '▣',
    description: 'Module registry config',
    primaryUrl: '/plugins',
    openMode: 'INTERNAL_ROUTE',
    roleRequired: ['ADMIN', 'MANAGER', 'VIEW_ONLY'],
    permissionRequired: 'PLUGIN_VIEW',
    isEnabled: true,
    isInternal: true,
    sortOrder: 90,
    status: 'ACTIVE',
    showInNav: true,
    navLabel: 'Cấu hình',
  },
];

export function getNavModules(modules: ModuleRegistryEntry[]): ModuleRegistryEntry[] {
  return modules.filter((m) => m.showInNav !== false && m.isEnabled);
}

export function findModuleByPath(modules: ModuleRegistryEntry[], pathname: string): ModuleRegistryEntry | null {
  const path = pathname.split('?')[0];
  if (path === '/m' || path.startsWith('/m/')) {
    const id = path.split('/')[2]?.toUpperCase().replace(/-/g, '_');
    return modules.find((m) => m.moduleId === id) ?? null;
  }
  const exact = modules.find((m) => m.primaryUrl === path);
  if (exact) return exact;
  if (path.startsWith('/tasks') || path.startsWith('/inbox')) {
    return modules.find((m) => m.moduleId === 'TASK') ?? null;
  }
  return null;
}

export const RUNTIME_TYPE_LABELS: Record<string, string> = {
  REACT: 'React',
  APPSHEET: 'AppSheet',
  WEBAPP: 'WebApp',
  GOOGLE_SHEET: 'Sheet',
  NOCODB: 'NocoDB',
  EXTERNAL: 'External',
};
