/**
 * CBV Core V2 Level 6 — constants (sheets, headers, statuses).
 * Dependencies: none
 */
var CBV_CORE_V2 = CBV_CORE_V2 || {};

CBV_CORE_V2.VERSION = '2.0.0-level6';

CBV_CORE_V2.SHEETS = {
  MODULE_REGISTRY: 'CBV_MODULE_REGISTRY',
  COMMAND_LOG: 'CBV_COMMAND_LOG',
  EVENT_QUEUE: 'CBV_EVENT_QUEUE',
  EVENT_LOG: 'CBV_EVENT_LOG',
  AUDIT_LOG: 'CBV_AUDIT_LOG',
  IDEMPOTENCY: 'CBV_IDEMPOTENCY',
  SYSTEM_HEALTH: 'CBV_SYSTEM_HEALTH',
  CONFIG_REGISTRY: 'CBV_CONFIG_REGISTRY'
};

CBV_CORE_V2.HEADERS = {
  MODULE_REGISTRY: [
    'MODULE_CODE', 'MODULE_NAME', 'STATUS', 'VERSION', 'ENTRY_HANDLER', 'OWNER', 'IS_LEVEL6', 'CREATED_AT', 'UPDATED_AT'
  ],
  COMMAND_LOG: [
    'COMMAND_ID', 'COMMAND_TYPE', 'MODULE_CODE', 'SOURCE', 'REQUEST_BY', 'PAYLOAD_JSON', 'IDEMPOTENCY_KEY',
    'STATUS', 'RESULT_JSON', 'ERROR_CODE', 'ERROR_MESSAGE', 'CREATED_AT', 'STARTED_AT', 'FINISHED_AT'
  ],
  EVENT_QUEUE: [
    'EVENT_ID', 'EVENT_TYPE', 'MODULE_CODE', 'ENTITY_TYPE', 'ENTITY_ID', 'SOURCE_COMMAND_ID', 'PAYLOAD_JSON',
    'STATUS', 'RETRY_COUNT', 'NEXT_RUN_AT', 'ERROR_CODE', 'CREATED_AT', 'PROCESSED_AT'
  ],
  EVENT_LOG: [
    'EVENT_ID', 'EVENT_TYPE', 'MODULE_CODE', 'ENTITY_TYPE', 'ENTITY_ID', 'SOURCE_COMMAND_ID', 'PAYLOAD_JSON',
    'CREATED_AT', 'CREATED_BY'
  ],
  AUDIT_LOG: [
    'AUDIT_ID', 'MODULE_CODE', 'ENTITY_TYPE', 'ENTITY_ID', 'ACTION', 'FIELD_NAME', 'OLD_VALUE', 'NEW_VALUE',
    'ACTOR_EMAIL', 'SOURCE', 'COMMAND_ID', 'CREATED_AT'
  ],
  IDEMPOTENCY: [
    'IDEMPOTENCY_KEY', 'COMMAND_TYPE', 'MODULE_CODE', 'STATUS', 'COMMAND_ID', 'RESULT_JSON', 'CREATED_AT', 'EXPIRED_AT'
  ],
  SYSTEM_HEALTH: [
    'CHECK_ID', 'MODULE_CODE', 'CHECK_NAME', 'SEVERITY', 'STATUS', 'MESSAGE', 'LAST_CHECK_AT', 'PAYLOAD_JSON'
  ],
  CONFIG_REGISTRY: [
    'CONFIG_KEY', 'MODULE_CODE', 'CONFIG_TYPE', 'CONFIG_JSON', 'IS_ACTIVE', 'UPDATED_AT'
  ]
};

CBV_CORE_V2.COMMAND_STATUS = {
  RECEIVED: 'RECEIVED',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  DUPLICATE: 'DUPLICATE'
};

CBV_CORE_V2.EVENT_QUEUE_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  DONE: 'DONE',
  FAILED: 'FAILED',
  DEAD_LETTER: 'DEAD_LETTER'
};

CBV_CORE_V2.IDEMPOTENCY_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PENDING: 'PENDING'
};

CBV_CORE_V2.EVENT_WORKER = {
  MAX_RETRY: 5,
  BATCH_LIMIT: 25
};

CBV_CORE_V2.MODULE_SEED_ROWS = [
  ['CONFIG', 'System Configuration', 'ACTIVE', 'V2_2', 'ConfigCommandHandler_handle', 'ADMIN', 'TRUE', '', ''],
  ['HOSO', 'Hồ sơ', 'ACTIVE', 'V2_2', 'HosoCommandHandler_handle', 'ADMIN', 'TRUE', '', ''],
  ['TASK', 'Công việc', 'LEGACY', 'v1.0', 'TaskLegacyHandler_handle', 'ADMIN', 'FALSE', '', ''],
  ['FINANCE', 'Thu chi', 'LEGACY', 'v1.0', 'FinanceLegacyHandler_handle', 'ADMIN', 'FALSE', '', '']
];

CBV_CORE_V2.ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MODULE_HANDLER_NOT_FOUND: 'MODULE_HANDLER_NOT_FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  HANDLER_EXCEPTION: 'HANDLER_EXCEPTION',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};
