/**
 * CONFIG module — physical CONFIG DB sheets + headers (main-control CONFIG_MANAGER PRO).
 * Data lives in spreadsheet CBV_CONFIG_DB_ID (not the Core control spreadsheet).
 * Dependencies: none
 */
var CBV_CONFIG_MODULE = CBV_CONFIG_MODULE || {};

CBV_CONFIG_MODULE.MODULE_CODE = 'CONFIG';
CBV_CONFIG_MODULE.VERSION = 'V2_2';

CBV_CONFIG_MODULE.TABLES = {
  ENV: 'CONFIG_ENV',
  MODULE: 'CONFIG_MODULE',
  SHEET_REGISTRY: 'CONFIG_SHEET_REGISTRY',
  ENUM: 'CONFIG_ENUM',
  RULE: 'CONFIG_RULE',
  FEATURE_FLAG: 'CONFIG_FEATURE_FLAG',
  ACCESS_LOG: 'CONFIG_ACCESS_LOG',
  CHANGE_LOG: 'CONFIG_CHANGE_LOG'
};

CBV_CONFIG_MODULE.HEADERS = {
  ENV: ['ENV_CODE', 'CONFIG_KEY', 'CONFIG_VALUE', 'IS_ACTIVE', 'UPDATED_AT'],
  MODULE: ['MODULE_CODE', 'DISPLAY_NAME', 'ACTIVE_VERSION', 'DB_CONFIG_KEY', 'STATUS'],
  SHEET_REGISTRY: ['MODULE_CODE', 'TABLE_CODE', 'SHEET_NAME', 'STATUS'],
  ENUM: ['ENUM_ID', 'ENUM_GROUP', 'ENUM_KEY', 'ENUM_VALUE', 'STATUS', 'CREATED_AT', 'UPDATED_AT'],
  RULE: ['RULE_ID', 'MODULE_CODE', 'RULE_KEY', 'RULE_TYPE', 'RULE_JSON', 'STATUS', 'CREATED_AT', 'UPDATED_AT'],
  FEATURE_FLAG: ['FLAG_KEY', 'FLAG_VALUE', 'STATUS', 'UPDATED_AT', 'UPDATED_BY'],
  ACCESS_LOG: ['LOG_ID', 'ACTOR_EMAIL', 'ACTION', 'RESOURCE_TYPE', 'RESOURCE_KEY', 'PAYLOAD_JSON', 'COMMAND_ID', 'CREATED_AT'],
  CHANGE_LOG: [
    'CHANGE_ID', 'ACTOR_EMAIL', 'CHANGE_TYPE', 'RESOURCE_TYPE', 'RESOURCE_KEY', 'OLD_VALUE', 'NEW_VALUE',
    'COMMAND_ID', 'PAYLOAD_JSON', 'CREATED_AT'
  ]
};
