/**
 * HO_SO V2 Real Service — constants (sheets, headers, enums).
 * Pilot on CBV Core V2; does not replace legacy HO_SO sheets usage in 10_HOSO_* .
 */
var HO_SO_V2 = HO_SO_V2 || {};

HO_SO_V2.SHEETS = {
  MASTER: 'HO_SO_MASTER',
  XA_VIEN: 'HO_SO_XA_VIEN',
  PHUONG_TIEN: 'HO_SO_PHUONG_TIEN',
  TAI_XE: 'HO_SO_TAI_XE',
  GIAY_TO: 'HO_SO_GIAY_TO',
  RELATION: 'HO_SO_RELATION',
  ATTACHMENT: 'HO_SO_ATTACHMENT',
  IMPORT_BATCH: 'HO_SO_IMPORT_BATCH',
  IMPORT_ROW_LOG: 'HO_SO_IMPORT_ROW_LOG',
  SEARCH_INDEX: 'HO_SO_SEARCH_INDEX',
  TEMPLATE: 'HO_SO_TEMPLATE',
  PRINT_JOB: 'HO_SO_PRINT_JOB',
  HEALTH: 'HO_SO_HEALTH'
};

HO_SO_V2.HEADERS = {
  MASTER: [
    'HO_SO_ID', 'HO_SO_CODE', 'HO_SO_TYPE', 'TITLE', 'PRIMARY_ENTITY_TYPE', 'PRIMARY_ENTITY_ID', 'STATUS', 'SOURCE',
    'OWNER_EMAIL', 'CREATED_AT', 'CREATED_BY', 'UPDATED_AT', 'UPDATED_BY', 'NOTE', 'META_JSON'
  ],
  XA_VIEN: [
    'XA_VIEN_ID', 'HO_SO_ID', 'HO_TEN', 'NAM_SINH', 'CCCD', 'CCCD_NGAY_CAP', 'CCCD_NOI_CAP', 'DIA_CHI', 'PHONE_1', 'PHONE_2',
    'EMAIL', 'NGUOI_DAI_DIEN', 'STATUS', 'CREATED_AT', 'UPDATED_AT', 'META_JSON'
  ],
  PHUONG_TIEN: [
    'PHUONG_TIEN_ID', 'HO_SO_ID', 'BIEN_SO', 'LOAI_XE', 'HIEU_XE', 'SO_LOAI', 'MAU_XE', 'NAM_SAN_XUAT', 'NUOC_SAN_XUAT',
    'SO_CHO_TAI_TRONG', 'SO_KHUNG', 'SO_MAY', 'GPS_WEB', 'GPS_USER', 'GPS_PASS', 'STATUS', 'CREATED_AT', 'UPDATED_AT', 'META_JSON'
  ],
  TAI_XE: [
    'TAI_XE_ID', 'HO_SO_ID', 'HO_TEN', 'CCCD', 'PHONE', 'GPLX_SO', 'GPLX_HANG', 'GPLX_NGAY_CAP', 'GPLX_NOI_CAP', 'DIA_CHI',
    'STATUS', 'CREATED_AT', 'UPDATED_AT', 'META_JSON'
  ],
  GIAY_TO: [
    'GIAY_TO_ID', 'HO_SO_ID', 'ENTITY_TYPE', 'ENTITY_ID', 'DOC_TYPE', 'DOC_NO', 'ISSUE_DATE', 'EXPIRE_DATE', 'STATUS',
    'FILE_URL', 'NOTE', 'CREATED_AT', 'UPDATED_AT', 'META_JSON'
  ],
  RELATION: [
    'RELATION_ID', 'FROM_TYPE', 'FROM_ID', 'TO_TYPE', 'TO_ID', 'RELATION_TYPE', 'STATUS', 'CREATED_AT', 'UPDATED_AT', 'META_JSON'
  ],
  ATTACHMENT: [
    'ATTACHMENT_ID', 'HO_SO_ID', 'ENTITY_TYPE', 'ENTITY_ID', 'FILE_TYPE', 'FILE_NAME', 'FILE_URL', 'DRIVE_FILE_ID',
    'MIME_TYPE', 'STATUS', 'CREATED_AT', 'CREATED_BY', 'NOTE', 'META_JSON'
  ],
  IMPORT_BATCH: [
    'BATCH_ID', 'SOURCE_TYPE', 'SOURCE_FILE_ID', 'SOURCE_FILE_NAME', 'STATUS', 'TOTAL_ROWS', 'SUCCESS_ROWS', 'ERROR_ROWS',
    'CREATED_AT', 'CREATED_BY', 'FINISHED_AT', 'META_JSON'
  ],
  IMPORT_ROW_LOG: [
    'ROW_LOG_ID', 'BATCH_ID', 'ROW_NO', 'STATUS', 'HO_SO_ID', 'ERROR_CODE', 'ERROR_MESSAGE', 'RAW_JSON', 'NORMALIZED_JSON', 'CREATED_AT'
  ],
  SEARCH_INDEX: [
    'SEARCH_ID', 'HO_SO_ID', 'ENTITY_TYPE', 'ENTITY_ID', 'TITLE', 'KEYWORDS', 'KEYWORDS_NORMALIZED', 'SOURCE_TABLE', 'STATUS',
    'UPDATED_AT', 'META_JSON'
  ],
  TEMPLATE: [
    'TEMPLATE_ID', 'TEMPLATE_CODE', 'TEMPLATE_NAME', 'TEMPLATE_TYPE', 'TEMPLATE_SOURCE_ID', 'TEMPLATE_SOURCE_URL', 'STATUS',
    'VERSION', 'CONFIG_JSON', 'CREATED_AT', 'UPDATED_AT'
  ],
  PRINT_JOB: [
    'PRINT_JOB_ID', 'HO_SO_ID', 'TEMPLATE_CODE', 'STATUS', 'OUTPUT_FILE_ID', 'OUTPUT_FILE_URL', 'OUTPUT_PDF_URL', 'ERROR_CODE',
    'ERROR_MESSAGE', 'CREATED_AT', 'CREATED_BY', 'FINISHED_AT', 'PAYLOAD_JSON'
  ],
  HEALTH: [
    'CHECK_ID', 'CHECK_NAME', 'SEVERITY', 'STATUS', 'MESSAGE', 'LAST_CHECK_AT', 'PAYLOAD_JSON'
  ]
};

HO_SO_V2.HO_SO_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED',
  CANCELLED: 'CANCELLED'
};

HO_SO_V2.IMPORT_STATUS = {
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  PARTIAL_SUCCESS: 'PARTIAL_SUCCESS',
  FAILED: 'FAILED'
};

HO_SO_V2.PRINT_JOB_STATUS = {
  PENDING: 'PENDING',
  PENDING_TEMPLATE: 'PENDING_TEMPLATE',
  RENDERING: 'RENDERING',
  DONE: 'DONE',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

HO_SO_V2.ATTACHMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  DELETED: 'DELETED'
};

HO_SO_V2.SEARCH_INDEX_STATUS = {
  ACTIVE: 'ACTIVE',
  DELETED: 'DELETED'
};

HO_SO_V2.ENTITY_STATUS = {
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED'
};

HO_SO_V2.RELATION_TYPE = {
  HO_SO_TO_XA_VIEN: 'HO_SO_TO_XA_VIEN',
  HO_SO_TO_PHUONG_TIEN: 'HO_SO_TO_PHUONG_TIEN',
  HO_SO_TO_TAI_XE: 'HO_SO_TO_TAI_XE',
  XA_VIEN_TO_PHUONG_TIEN: 'XA_VIEN_TO_PHUONG_TIEN',
  TAI_XE_TO_PHUONG_TIEN: 'TAI_XE_TO_PHUONG_TIEN'
};

HO_SO_V2.PRINT_ALLOW_PENDING_WITHOUT_TEMPLATE = true;

HO_SO_V2.ID_PREFIX = {
  HO_SO: 'HS',
  XA_VIEN: 'XV',
  PHUONG_TIEN: 'PT',
  TAI_XE: 'TX',
  GIAY_TO: 'GT',
  ATTACHMENT: 'ATT',
  BATCH: 'IMP',
  PRINT_JOB: 'PRN',
  SEARCH: 'SRCH',
  RELATION: 'REL',
  ROW_LOG: 'RL'
};

/** CONFIG adapter context (command.source / MENU / TEST); default HOSO_SERVICE. */
var hoSoV2RuntimeSource_ = 'HOSO_SERVICE';

/**
 * @param {string} [src]
 */
function hoSoV2SetRuntimeSource_(src) {
  hoSoV2RuntimeSource_ = (src && String(src).trim()) || 'HOSO_SERVICE';
}

/**
 * @returns {{ source: string }}
 */
function hoSoV2GetRuntimeConfigContext_() {
  return { source: hoSoV2RuntimeSource_ };
}
